# java test.BSOAuthenticate
#
# Regression tests for 6163T
#

# Do not do cleanup.  It deletes the library
# JDCleanupTest

JDDriverTest

JDBIDITestcase
#
# Remove this later 
#

JDConnectionTest
JDStatementTest



# Don't run parm tests 
# JDParmTest
#

JDBUTest
JDCSTest

JDPSTest
JDRSTest
JDRSStressTest
JDRSMDTest

JDDMDTest

JDPMDTest
JDLobTest
#
# Don't run TC tests -- native only 
# JDTCTest
# 
JDDSTest

# Need to cleanup for JTA tests 
# Do not run JTA.  It drops the collection 
#java JTACleanupTx `hostname | sed 's/\..*//'` ThisIsDangerous all      
#JTAStdTest
#JTATest
# More JTA Cleanup
# java JTACleanupTx `hostname | sed 's/\..*//'` ThisIsDangerous all      

# Run these later
# JDJSTPTest
JDSavepointTest
JDASPTest

# Toolbox only tests 
AS400JDBCConnectionPoolTest
AS400JDBCDataSourceTest
AS400JDBCRowSetTest
# Test stand alone programs
JDJSTPjdbc 
