# java test.BSOAuthenticate
#
# Regression tests for 7153V
#

JDCleanupTest
JDDriverTest

JDBIDITestcase

JDConnectionTest

#JDStatementTest
#Run all but JDStatementPackageCache
JDStatementBatch
JDStatementClose
JDStatementCursorName
JDStatementDelimiters
JDStatementDRDA
JDStatementExceptions
JDStatementExecute
JDStatementGetGeneratedKeys
JDStatementGetGeneratedKeys2
JDStatementMisc
JDStatementMisc2
JDStatementResults
JDStatementStressTest
JDStatementWarnings
JDStatementWrapper


# Don't run parm tests 
# JDParmTest
#

JDBUTest
JDCSTest

# JDPSTest
# Don't run JDRowSetPSTestcase for proxy 
JDPSBatch
JDPSBatchNative
JDPSBatchStress
JDPSClearParameters
JDPSClose
JDPSDataTruncation
JDPSExecute
JDPSMisc
JDPSResults
JDPSSetArray
JDPSSetAsciiStream
JDPSSetBigDecimal
JDPSSetBinaryStream
JDPSSetBlob40
JDPSSetBlob
JDPSSetBoolean
JDPSSetByte
JDPSSetBytes
JDPSSetCharacterStream
JDPSSetClob40
JDPSSetClob
JDPSSetDB2Default
JDPSSetDB2Unassigned
JDPSSetDBDefault
JDPSSetDBUnassigned
JDPSSetDate
JDPSSetDouble
JDPSSetFloat
JDPSSetInt
JDPSSetLong
JDPSSetNCharacterStream
JDPSSetNClob
JDPSSetNString
JDPSSetNull
JDPSSetObject2
JDPSSetObject3
JDPSSetObject4
JDPSSetRef
JDPSSetRowId
JDPSSetSQLXML
JDPSSetShort
JDPSSetString
JDPSSetTime
JDPSSetTimestamp
JDPSSetUnicodeStream
# JDRowSetPSTestcase



# JDRSTest
# Don't run JDRowSetRSTestcase for proxy
JDRSAbsolute
JDRSAfterLast
JDRSBeforeFirst
JDRSCachedRowSet
JDRSCursorScroll
JDRSCursorScrollSensitiveFromCall
JDRSCursorScrollInsensitiveFromCall
JDRSCursorSensitivity
JDRSDataCompression
JDRSDeleteRow
JDRSFetchSize
JDRSFindColumn
JDRSFirst
JDRSGetArray
JDRSGetAsciiStream
JDRSGetBigDecimal
JDRSGetBinaryStream
JDRSGetBlob
JDRSGetBoolean
JDRSGetByte
JDRSGetBytes
JDRSGetBytesBinary
JDRSGetCharacterStream
JDRSGetClob
JDRSGetDate
JDRSGetDouble
JDRSGetFloat
JDRSGetInt
JDRSGetLong
JDRSGetNCharacterStream
JDRSGetNClob
JDRSGetNString
JDRSGetObject
JDRSGetRef
JDRSGetRow
JDRSGetRowId
JDRSGetSQLXML
JDRSGetShort
JDRSGetString
JDRSGetTime
JDRSGetTimestamp
JDRSGetURL
JDRSGetUnicodeStream
JDRSInsertRow
JDRSLast
JDRSMisc
JDRSMoveToCurrentRow
JDRSMoveToInsertRow
JDRSNext
JDRSPrevious
JDRSRefreshRow
JDRSRelative
JDRSStress
JDRSStressDirectMap
JDRSStressNoBlockPSDirectMap
JDRSStressPS
JDRSStressPSDirectMap
JDRSStressScroll
JDRSStressScrollDirectMap
JDRSStressScrollPS
JDRSStressScrollPSDirectMap
JDRSStressUpdatePS
JDRSStressUpdatePSDirectMap
JDRSUpdateAsciiStream
JDRSUpdateBigDecimal
JDRSUpdateBinaryStream
JDRSUpdateBoolean
JDRSUpdateByte
JDRSUpdateBytes
JDRSUpdateCharacterStream
JDRSUpdateClob
JDRSUpdateDB2Default
JDRSUpdateDBDefault
JDRSUpdateDate
JDRSUpdateDouble
JDRSUpdateFloat
JDRSUpdateInt
JDRSUpdateLong
JDRSUpdateNCharacterStream
JDRSUpdateNClob
JDRSUpdateNString
JDRSUpdateNull
JDRSUpdateObject
JDRSUpdateRow
JDRSUpdateRowId
JDRSUpdateSQLXML
JDRSUpdateShort
JDRSUpdateString
JDRSUpdateTime
JDRSUpdateTimestamp
JDRSWarnings
JDRSWasNull
JDRSWrapper
# JDRowSetRSTestcase


JDRSMDTest

JDDMDTest

JDPMDTest
JDLobTest
#
# Don't run TC tests -- native only 
# JDTCTest
# 
# Don't run JDDSTest for proxy. 
# JDDSTest

# Run these later
# JDJSTPTest
JDSavepointTest

JDASPTest
