///////////////////////////////////////////////////////////////////////////////
//
// JTOpen (IBM Toolbox for Java - OSS version)
//
// Filename:  CommandHelpRetrieverTestcase.java
//
// The source code contained herein is licensed under the IBM Public License
// Version 1.0, which has been approved by the Open Source Initiative.
// Copyright (C) 1997-2023 International Business Machines Corporation and
// others.  All rights reserved.
//
///////////////////////////////////////////////////////////////////////////////

package test.Cmd;


import java.io.FileOutputStream;
import java.util.Vector;

import com.ibm.as400.access.AS400;
import com.ibm.as400.access.Command;
import com.ibm.as400.access.CommandList;
import com.ibm.as400.util.CommandHelpRetriever;


import test.Testcase;

/**
  Testcase CommandHelpRetrieverTestcase.
 **/
public class CommandHelpRetrieverTestcase extends Testcase
{
  public static void main(String args[]) throws Exception {
    String[] newArgs = new String[args.length+2];
     newArgs[0] = "-tc";
     newArgs[1] = "CommandHelpRetrieverTestcase";
     for (int i = 0; i < args.length; i++) {
       newArgs[2+i]=args[i];
     }
     test.CommandHelpTest.main(newArgs); 
   }
   boolean rejectChange = false;
   
   /**
     Constructor.  This is called from the HTMLTest constructor.
    **/
   public CommandHelpRetrieverTestcase(AS400 systemObject,
                                 Vector<String> variationsToRun,
                                 int runMode,
                                 FileOutputStream fileOutputStream)
   {
      super(systemObject, "CommandHelpRetrieverTestcase", variationsToRun,
            runMode, fileOutputStream);
   }

   
   
   /**
     Successful construction of an CommandHelpRetriever using the default ctor.

     CommandHelpRetriever()
    **/
   public void Var001()
   {
      try
      {
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         assertCondition(true, commandHelp.toString()); 
      }
      catch(Exception e)
      {
         failed(e, "Unexpected exception.");
      }
   }

   
   /**
     Construct an CommandHelpRetriever with the default ctor.
     Set debug and rretrieve it to verify setting.
     
     CommandHelpRetriever()
     CommandHelpRetriever::setDebug(boolean)
     CommandHelpRetriever::getCommand()
    **/
   public void Var002()
   {
      try
      {
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         commandHelp.setDebug(true);
         if (commandHelp.getDebug())
             succeeded();
         else
            failed("Incorrect parameter value returned.");
      }
      catch(Exception e)
      {
         failed(e, "Unexpected exception.");
      }
   }

   /**
     Construct an CommandHelpRetriever with the default ctor.
     Set the showchoicepgmvalues and retrieve it to verify setting.
     
     CommandHelpRetriever()
     CommandHelpRetriever::setShowChoiceProgramValues(true)
     CommandHelpRetriever::getShowChoiceProgramValues()
    **/
   public void Var003()
   {
      try
      {
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         commandHelp.setShowChoiceProgramValues(true);
         if (commandHelp.getShowChoiceProgramValues())
            succeeded();
         else
            failed("Incorrect parameter value returned.");
      }
      catch(Exception e)
      {
         failed(e, "Unexpected exception.");
      }
   }

   /**
     Construct an CommandHelpRetriever with the default ctor.
     Set the outputlocation and retrieve it to verify setting.
     
     CommandHelpRetriever()
     CommandHelpRetriever::setOutputLocation(String)
     CommandHelpRetriever::getOutputLocation()
    **/
   public void Var004()
   {
      try
      {
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         commandHelp.setOutputLocation("c:\\java");
         if (commandHelp.getOutputLocation().equals("c:\\java"))
            succeeded();
         else
            failed("Incorrect parameter value returned.");
      }
      catch(Exception e)
      {
         failed(e, "Unexpected exception.");
      }
   }
   
   
   /**
     Construct an CommandHelpRetriever with the default ctor.
     Set the outputLocation with a null parm.
     A NullPointerException should be thrown
     
     CommandHelpRetriever()
     CommandHelpRetriever::setOutputLocation(jull)
     **/
   public void Var005()
   {
      try
      {
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         commandHelp.setOutputLocation(null);
         failed("No Exception.");
      }
      catch(Exception e)
      {
         if (exceptionIs(e, "NullPointerException", "location"))
            succeeded();
         else
            failed(e, "Wrong exception info.");
      }
   }

   
   /**
     Construct an CommandHelpRetriever with the data and commandHelp parm.
     
     CommandHelpRetriever(AS400, String, String)
     CommandHelpRetriever::generateList()
    **/
   public void Var006()
   {
      try
      {
         // create a CommandHelpRetriever
         CommandHelpRetriever commandHelp = new CommandHelpRetriever();
         CommandList cmdList = new CommandList(systemObject_, "qsys", "crtlib");
         Command[] cmds = cmdList.generateList();

         String help = commandHelp.generateHTML(cmds[0]);

         if (help != null && help.length() != 0)
             succeeded();
         else
             failed("Command help is empty or null");
         
      }
      catch(Exception e)
      {
         failed(e, "Unexpected exception.");
      }
   }

   /**
    * run generateHTML on a command that does not have any help. 
    */ 
   public void Var007() { 

       try
       {
	   String []expectedStrings = {
	       "<title>Turn on All Auditing",
	   } ;

	   boolean passed = true;
	   StringBuffer sb = new StringBuffer("New testcases added 1/21/2011 to detect CPS 883RL9.  Fixed JTOpen 7.4\n");
	   
	 // create a CommandHelpRetriever
	   CommandHelpRetriever commandHelp = new CommandHelpRetriever();
	   CommandList cmdList = new CommandList(systemObject_, "qdevelop", "allaudon");
	   Command[] cmds = cmdList.generateList();

	   String help = commandHelp.generateHTML(cmds[0]);

	   if (help == null) {
	       sb.append("Command help is empty\n");
	       passed = false; 
	   } else {
	       sb.append("Returned help : "+help+"\n"); 
	       for (int i = 0; i < expectedStrings.length; i++) {
		   if (help.indexOf(expectedStrings[i]) < 0) {
		       sb.append("Did not find expected string "+expectedStrings[i]+"\n");
		       passed = false; 
		   } 
	       }
	   } 

	   assertCondition(passed, sb.toString());

       }
       catch(Exception e)
       {
	   failed(e, "Unexpected exception.");

	   Throwable cause = e.getCause();
	   while (cause != null) {
	       System.out.flush(); 
	       System.err.flush();
	       System.out.println("Caused by ");
	       System.out.flush();
	       System.err.flush(); 
	       cause.printStackTrace();
	       cause = cause.getCause();
	   } 

       }


   }

   /**
    * run generateHTML on a various commands in QDEVELOP.
    */ 
   public void Var008() { 

       StringBuffer sb = new StringBuffer("New testcases added   Fixed JTOpen 7.4\n");

       try
       {
	   String [][] commandsAndExpectedStrings = {
	       {"AJ", "<h2>Work with Active Jobs"},
	       {"ADDLIBL", "<title>Add to library list", "ADDLIBL is a front end build tool to the ADDLIBLE command"},
	       {"APYGRP", "<title>Apply PTF Group", "APYGRP.COMMAND.EXAMPLES"},
	       {"BR", "<title>Browse a Test Case Member", "This command will allow the user to browse the test case member source code using SEU."},
	       {"CCSIDINFO", "<title>EXTRACT CCSID INFORMATION" },
	       {"CHKASP", "<h2>Check ASP Status and Usage", "The Check Auxiliary Storage Pool (CHKASP) command can be used to determine the ASP Status and Usage."},
	       {"DBCLOSE", "<title>Data Base Close", "All environments"},

	       {"GETOBJ", "The Get Object (GETOBJ) command uses the File Transfer Protocol supplied by TCP/IP"},
	       {"JL",     "<title>Display the Joblog ", "This command will allow the user to display the most current joblog of a specified test case"},
	       {"LSTOBJ", "<title>List Objects in Lib", "capability to search for and return information about libraries"},
	       {"PROBE",  "<title>Probe BATS Problems"},
	       {"PRTJOB", "<title>PRINT PROCESS DUMP OF JOB"},
	       {"PUTIFS", "<title>Put IFS objects to an iSeries"},
	       {"READ",   "<title>Data Base Get"},
	       {"RTVAUT", "<title>Retrieve Authority"},
	       {"SIGNAL", "<title>Signal an Escape Message"}, 
	       
	   } ;

	   boolean passed = true;
	   
 	   // create a CommandHelpRetriever
	   for (int commandIndex = 0; commandIndex < commandsAndExpectedStrings.length; commandIndex++) {
	       String[] commandAndExpected = commandsAndExpectedStrings[commandIndex]; 

	       CommandHelpRetriever commandHelp = new CommandHelpRetriever();
	       CommandList cmdList = new CommandList(systemObject_, "qdevelop", commandAndExpected[0]);
	       Command[] cmds = cmdList.generateList();

	       sb.append("\n-->Command="+commandAndExpected[0]+"\n"); 
	       String help = commandHelp.generateHTML(cmds[0]);

	       if (help == null) {
		   sb.append("Command help is empty\n");
		   passed = false; 
	       } else {
		   sb.append("Returned help : "+help+"\n"); 
		   for (int i = 1; i < commandAndExpected.length; i++) {
		       if (help.indexOf(commandAndExpected[i]) < 0) {
			   sb.append("Did not find expected string "+commandAndExpected[i]+"\n");
			   passed = false; 
		       } 
		   }
	       } 
	   }
	   assertCondition(passed, sb.toString());

       }
       catch(Exception e)
       {
	   failed(e, "Unexpected exception."+sb.toString());

	   System.out.flush(); 
	   System.err.flush();
	   System.out.println("===================================="); 
	   System.out.flush(); 
	   System.err.flush();
	   Throwable cause = e.getCause();
	   while (cause != null) {
	       System.out.flush(); 
	       System.err.flush();
	       System.out.println("Caused by ");
	       System.out.flush();
	       System.err.flush(); 
	       cause.printStackTrace();
	       cause = cause.getCause();
	   } 

       }


   }


   /**
    * run generateHTML on a various commands in QSYS.
    */ 
   public void Var009() { 

       StringBuffer sb = new StringBuffer("New testcases added   Fixed JTOpen 7.4\n");

       try
       {

         // 
	 // this list create on V5R4 using
	 //   system "dspobjd qsys/*all *cmd" | grep CMD | sed 's/^ *\([^ ][^ ]*\) *.CMD.*/{"\1","\1"},/'
         //   
    	   StringBuffer failList = new StringBuffer(); 
	   String [][] commandsAndExpectedStrings = {

	       {"ADDAJE","ADDAJE"},
	       {"ADDALRACNE","ADDALRACNE"},
	       {"ADDALRD","ADDALRD"},
	       {"ADDALRSLTE","ADDALRSLTE"},
	       {"ADDAUTLE","ADDAUTLE"},
	       {"ADDBKP","ADDBKP"},
	       {"ADDBLDOPTE","ADDBLDOPTE"},
	       {"ADDBNDDIRE","ADDBNDDIRE"},
	       {"ADDBUILDER","ADDBUILDER"},
	       {"ADDCFGLE","ADDCFGLE"},
	       {"ADDCKMKSFE","ADDCKMKSFE"},
	       {"ADDCMNE","ADDCMNE"},
	       {"ADDCOMSNMP","ADDCOMSNMP"},
	       {"ADDDIRE","ADDDIRE"},
	       {"ADDDIRSHD","ADDDIRSHD"},
	       {"ADDDLOAUT","ADDDLOAUT"},
	       // {"ADDDPRREG","ADDDPRREG"},
	       // {"ADDDPRSUB","ADDDPRSUB"},
	       // {"ADDDPRSUBM","ADDDPRSUBM"},
	       {"ADDDSTLE","ADDDSTLE"},
	       {"ADDDTADFN","ADDDTADFN"},
	       {"ADDEMLCFGE","ADDEMLCFGE"},
	       {"ADDENVVAR","ADDENVVAR"},
	       {"ADDEWCBCDE","ADDEWCBCDE"},
	       {"ADDEWCM","ADDEWCM"},
	       {"ADDEWCPTCE","ADDEWCPTCE"},
	       {"ADDEWLM","ADDEWLM"},
	       // {"ADDFAXCRD","ADDFAXCRD"},
	       // {"ADDFAXDLE","ADDFAXDLE"},
	       // {"ADDFCTE","ADDFCTE"},
	       {"ADDFNTTBLE","ADDFNTTBLE"},
	       {"ADDHDBDLFM","ADDHDBDLFM"},
	       {"ADDICFDEVE","ADDICFDEVE"},
	       {"ADDIMGCLGE","ADDIMGCLGE"},
	       {"ADDIPSIFC","ADDIPSIFC"},
	       {"ADDIPSLOC","ADDIPSLOC"},
	       {"ADDIPSRTE","ADDIPSRTE"},
	       {"ADDJOBJS","ADDJOBJS"},
	       {"ADDJOBQE","ADDJOBQE"},
	       {"ADDJOBSCDE","ADDJOBSCDE"},
	       {"ADDKRBKTE","ADDKRBKTE"},
	       {"ADDKRBTKT","ADDKRBTKT"},
	       {"ADDLANADPI","ADDLANADPI"},
	       {"ADDLFM","ADDLFM"},
	       {"ADDLIBLE","ADDLIBLE"},
	       {"ADDLNK","ADDLNK"},
	       {"ADDMEDBRM","ADDMEDBRM"},
	       {"ADDMEDIBRM","ADDMEDIBRM"},
	       {"ADDMLMBRM","ADDMLMBRM"},
	       {"ADDMSGD","ADDMSGD"},
	       {"ADDNCK","ADDNCK"},
	       {"ADDNETTBLE","ADDNETTBLE"},
	       {"ADDNODLE","ADDNODLE"},
	       {"ADDNWSSTGL","ADDNWSSTGL"},
	       {"ADDOSPFARA","ADDOSPFARA"},
	       {"ADDOSPFIFC","ADDOSPFIFC"},
	       {"ADDOSPFLNK","ADDOSPFLNK"},
	       {"ADDOSPFRNG","ADDOSPFRNG"},
	       {"ADDPCLTBLE","ADDPCLTBLE"},
	       {"ADDPFCST","ADDPFCST"},
	       {"ADDPFM","ADDPFM"},
	       {"ADDPFTRG","ADDPFTRG"},
	       {"ADDPFVLM","ADDPFVLM"},
	       {"ADDPFXDLFM","ADDPFXDLFM"},
	       {"ADDPGM","ADDPGM"},
	       {"ADDPJE","ADDPJE"},
	       {"ADDPRBACNE","ADDPRBACNE"},
	       {"ADDPRBSLTE","ADDPRBSLTE"},
	       {"ADDPRDBPR","ADDPRDBPR"},
	       {"ADDRDBDIRE","ADDRDBDIRE"},
	       {"ADDREXBUF","ADDREXBUF"},
	       {"ADDRIPACP","ADDRIPACP"},
	       {"ADDRIPFLT","ADDRIPFLT"},
	       {"ADDRIPIFC","ADDRIPIFC"},
	       {"ADDRIPIGN","ADDRIPIGN"},
	       {"ADDRJECMNE","ADDRJECMNE"},
	       {"ADDRJERDRE","ADDRJERDRE"},
	       {"ADDRJEWTRE","ADDRJEWTRE"},
	       {"ADDRMTJRN","ADDRMTJRN"},
	       {"ADDRPYLE","ADDRPYLE"},
	       {"ADDRTGE","ADDRTGE"},
	       {"ADDSCHIDXE","ADDSCHIDXE"},
	       {"ADDSMTPLE","ADDSMTPLE"},
	       {"ADDSOCE","ADDSOCE"},
	       {"ADDSRVTBLE","ADDSRVTBLE"},
	       {"ADDSVRAUTE","ADDSVRAUTE"},
	       {"ADDTAPCTG","ADDTAPCTG"},
	       {"ADDTCPHTE","ADDTCPHTE"},
	       {"ADDTCPIFC","ADDTCPIFC"},
	       {"ADDTCPPORT","ADDTCPPORT"},
	       {"ADDTCPPTP","ADDTCPPTP"},
	       {"ADDTCPRSI","ADDTCPRSI"},
	       {"ADDTCPRTE","ADDTCPRTE"},
	       {"ADDTCPSVR","ADDTCPSVR"},
	       {"ADDTEFE","ADDTEFE"},
	       {"ADDTRC","ADDTRC"},
	       {"ADDWSE","ADDWSE"},
	       {"ALCOBJ","ALCOBJ"},
	       {"ANSLIN","ANSLIN"},
	       // Not Authorized to object ANZDBF in QPFR  {"ANZDBF","ANZDBF"},
	       // Not Authorized to object ANZDBFKEY in QPFR {"ANZDBFKEY","ANZDBFKEY"},
	       {"ANZDPRJRN","ANZDPRJRN"},
	       {"ANZJVAPGM","ANZJVAPGM"},
	       {"ANZLIBBRM","ANZLIBBRM"},
	       // Not autorized {"ANZPFRDTA","ANZPFRDTA"},
	       // Not autorized {"ANZPGM","ANZPGM"},
	       {"ANZQRY","ANZQRY"},
	       {"APING","APING"},
	       {"AREXEC","AREXEC"},
	       {"ARPING","ARPING"},
	       {"ASKQST","ASKQST"},
	       {"BCHJOB","BCHJOB"},
	       {"BLDHELP","BLDHELP"},
	       {"CALL","CALL"},
	       {"CALLPRC","CALLPRC"},
	       {"CALLSUBR","CALLSUBR"},
	       // Not autorized {"CCTMQM","CCTMQM"},
	       {"CD","CD"},
	       {"CFGDEVMLB","CFGDEVMLB"},
	       // {"CFGFAXSRV","CFGFAXSRV"},
	       {"CFGHTTPSCH","CFGHTTPSCH"},
	       {"CFGIPS","CFGIPS"},
	       {"CFGPMAGT","CFGPMAGT"},
	       {"CFGPMLIN","CFGPMLIN"},
	       {"CFGPM400","CFGPM400"},
	       // Not autorized {"CFGRPDS","CFGRPDS"},
	       {"CFGRTG","CFGRTG"},
	       {"CFGTCP","CFGTCP"},
	       {"CFGTCPAPP","CFGTCPAPP"},
	       {"CFGTCPBP","CFGTCPBP"},
	       {"CFGTCPFTP","CFGTCPFTP"},
	       {"CFGTCPHTTP","CFGTCPHTTP"},
	       {"CFGTCPLPD","CFGTCPLPD"},
	       {"CFGTCPPTP","CFGTCPPTP"},
	       {"CFGTCPRTD","CFGTCPRTD"},
	       {"CFGTCPRXC","CFGTCPRXC"},
	       {"CFGTCPSMTP","CFGTCPSMTP"},
	       {"CFGTCPSNMP","CFGTCPSNMP"},
	       {"CFGTCPTELN","CFGTCPTELN"},
	       {"CHDIR","CHDIR"},
	       {"CHGACGCDE","CHGACGCDE"},
	       {"CHGAJE","CHGAJE"},
	       {"CHGALRACNE","CHGALRACNE"},
	       {"CHGALRD","CHGALRD"},
	       {"CHGALRSLTE","CHGALRSLTE"},
	       {"CHGALRTBL","CHGALRTBL"},
	       {"CHGASPACT","CHGASPACT"},
	       {"CHGATR","CHGATR"},
	       {"CHGAUD","CHGAUD"},
	       {"CHGAUT","CHGAUT"},
	       {"CHGAUTJS","CHGAUTJS"},
	       {"CHGAUTLE","CHGAUTLE"},
	       {"CHGBCKUP","CHGBCKUP"},
	       {"CHGBLDMSG","CHGBLDMSG"},
	       {"CHGBLDOPTE","CHGBLDOPTE"},
	       {"CHGBPA","CHGBPA"},
	       {"CHGBPR","CHGBPR"},
	       {"CHGBUILDER","CHGBUILDER"},
	       {"CHGCDEFNT","CHGCDEFNT"},
	       {"CHGCFGL","CHGCFGL"},
	       {"CHGCFGLE","CHGCFGLE"},
	       {"CHGCLNUP","CHGCLNUP"},
	       {"CHGCLS","CHGCLS"},
	       {"CHGCLURCY","CHGCLURCY"},
	       {"CHGCMD","CHGCMD"},
	       {"CHGCMDDFT","CHGCMDDFT"},
	       {"CHGCMNE","CHGCMNE"},
	       {"CHGCOMSNMP","CHGCOMSNMP"},
	       {"CHGCOSD","CHGCOSD"},
	       {"CHGCRQD","CHGCRQD"},
	       {"CHGCSI","CHGCSI"},
	       {"CHGCTLAPPC","CHGCTLAPPC"},
	       {"CHGCTLASC","CHGCTLASC"},
	       {"CHGCTLBSC","CHGCTLBSC"},
	       {"CHGCTLFNC","CHGCTLFNC"},
	       {"CHGCTLHOST","CHGCTLHOST"},
	       {"CHGCTLLWS","CHGCTLLWS"},
	       {"CHGCTLNET","CHGCTLNET"},
	       {"CHGCTLRTL","CHGCTLRTL"},
	       {"CHGCTLRWS","CHGCTLRWS"},
	       {"CHGCTLTAP","CHGCTLTAP"},
	       {"CHGCTLVWS","CHGCTLVWS"},
	       {"CHGCURDIR","CHGCURDIR"},
	       {"CHGCURLIB","CHGCURLIB"},
	       {"CHGDBG","CHGDBG"},
	       {"CHGDDMF","CHGDDMF"},
	       {"CHGDDMTCPA","CHGDDMTCPA"},
	       {"CHGDEVAPPC","CHGDEVAPPC"},
	       {"CHGDEVASC","CHGDEVASC"},
	       {"CHGDEVASP","CHGDEVASP"},
	       {"CHGDEVBSC","CHGDEVBSC"},
	       {"CHGDEVCRP","CHGDEVCRP"},
	       {"CHGDEVDKT","CHGDEVDKT"},
	       {"CHGDEVDSP","CHGDEVDSP"},
	       {"CHGDEVFNC","CHGDEVFNC"},
	       {"CHGDEVHOST","CHGDEVHOST"},
	       {"CHGDEVINTR","CHGDEVINTR"},
	       {"CHGDEVMLB","CHGDEVMLB"},
	       {"CHGDEVNET","CHGDEVNET"},
	       {"CHGDEVNWSH","CHGDEVNWSH"},
	       {"CHGDEVOPT","CHGDEVOPT"},
	       {"CHGDEVPRT","CHGDEVPRT"},
	       {"CHGDEVRTL","CHGDEVRTL"},
	       {"CHGDEVSNPT","CHGDEVSNPT"},
	       {"CHGDEVSNUF","CHGDEVSNUF"},
	       {"CHGDEVTAP","CHGDEVTAP"},
	       {"CHGDHCPA","CHGDHCPA"},
	       {"CHGDIRE","CHGDIRE"},
	       {"CHGDIRSHD","CHGDIRSHD"},
	       {"CHGDKTF","CHGDKTF"},
	       {"CHGDLJS","CHGDLJS"},
	       {"CHGDLOAUD","CHGDLOAUD"},
	       {"CHGDLOAUT","CHGDLOAUT"},
	       {"CHGDLOOWN","CHGDLOOWN"},
	       {"CHGDLOPGP","CHGDLOPGP"},
	       {"CHGDNSA","CHGDNSA"},
	       {"CHGDOCD","CHGDOCD"},
	       {"CHGDSPF","CHGDSPF"},
	       {"CHGDSTA","CHGDSTA"},
	       {"CHGDSTD","CHGDSTD"},
	       {"CHGDSTL","CHGDSTL"},
	       {"CHGDSTOWN","CHGDSTOWN"},
	       {"CHGDSTPWD","CHGDSTPWD"},
	       {"CHGDTA","CHGDTA"},
	       {"CHGDTAARA","CHGDTAARA"},
	       {"CHGDTAJS","CHGDTAJS"},
	       {"CHGEMLCFGE","CHGEMLCFGE"},
	       {"CHGENVVAR","CHGENVVAR"},
	       {"CHGEWCBCDE","CHGEWCBCDE"},
	       {"CHGEWCM","CHGEWCM"},
	       {"CHGEWCPTCE","CHGEWCPTCE"},
	       {"CHGEWLM","CHGEWLM"},
	       // {"CHGFAXFA","CHGFAXFA"},
	       // {"CHGFAXSDA","CHGFAXSDA"},
	       // Not autorized {"CHGFCNARA","CHGFCNARA"},
	       {"CHGFCNUSG","CHGFCNUSG"},
	       {"CHGFCT","CHGFCT"},
	       {"CHGFCTE","CHGFCTE"},
	       {"CHGFNTRSC","CHGFNTRSC"},
	       {"CHGFNTTBLE","CHGFNTTBLE"},
	       {"CHGFTPA","CHGFTPA"},
	       {"CHGFTR","CHGFTR"},
	       // Not autorized {"CHGGPHFMT","CHGGPHFMT"},
	       // Not autorized {"CHGGPHPKG","CHGGPHPKG"},
	       {"CHGGRPA","CHGGRPA"},
	       {"CHGHLLPTR","CHGHLLPTR"},
	       {"CHGHTTPA","CHGHTTPA"},
	       {"CHGICFDEVE","CHGICFDEVE"},
	       {"CHGICFF","CHGICFF"},
	       {"CHGIMGCLG","CHGIMGCLG"},
	       {"CHGIMGCLGE","CHGIMGCLGE"},
	       {"CHGIPSIFC","CHGIPSIFC"},
	       {"CHGIPSLOC","CHGIPSLOC"},
	       {"CHGIPSTOS","CHGIPSTOS"},
	       {"CHGJOB","CHGJOB"},
	       {"CHGJOBD","CHGJOBD"},
	       {"CHGJOBJS","CHGJOBJS"},
	       {"CHGJOBMLBA","CHGJOBMLBA"},
	       {"CHGJOBQ","CHGJOBQ"},
	       {"CHGJOBQE","CHGJOBQE"},
	       {"CHGJOBSCDE","CHGJOBSCDE"},
	       // Not autorized {"CHGJOBTYP","CHGJOBTYP"},
	       {"CHGJRNOBJ","CHGJRNOBJ"},
	       {"CHGJVAPGM","CHGJVAPGM"},
	       {"CHGKBDMAP","CHGKBDMAP"},
	       {"CHGKRBPWD","CHGKRBPWD"},
	       {"CHGLANADPI","CHGLANADPI"},
	       {"CHGLF","CHGLF"},
	       {"CHGLFM","CHGLFM"},
	       {"CHGLIB","CHGLIB"},
	       {"CHGLIBL","CHGLIBL"},
	       {"CHGLINASC","CHGLINASC"},
	       {"CHGLINBSC","CHGLINBSC"},
	       {"CHGLINDDI","CHGLINDDI"},
	       {"CHGLINETH","CHGLINETH"},
	       // {"CHGLINFAX","CHGLINFAX"},
	       {"CHGLINFR","CHGLINFR"},
	       {"CHGLINPPP","CHGLINPPP"},
	       {"CHGLINSDLC","CHGLINSDLC"},
	       {"CHGLINTDLC","CHGLINTDLC"},
	       {"CHGLINTRN","CHGLINTRN"},
	       {"CHGLINWLS","CHGLINWLS"},
	       {"CHGLINX25","CHGLINX25"},
	       // Not autorized {"CHGLNKLBRM","CHGLNKLBRM"},
	       {"CHGLPDA","CHGLPDA"},
	       {"CHGMEDBRM","CHGMEDBRM"},
	       {"CHGMLEOWN","CHGMLEOWN"},
	       {"CHGMNU","CHGMNU"},
	       {"CHGMOD","CHGMOD"},
	       {"CHGMODD","CHGMODD"},
	       // Not autorized {"CHGMQM","CHGMQM"},
	       // Not autorized {"CHGMQMAUTI","CHGMQMAUTI"},
	       // Not autorized {"CHGMQMCHL","CHGMQMCHL"},
	       // Not autorized {"CHGMQMLSR","CHGMQMLSR"},
	       // Not autorized {"CHGMQMNL","CHGMQMNL"},
	       // Not autorized {"CHGMQMPRC","CHGMQMPRC"},
	       // Not autorized {"CHGMQMQ","CHGMQMQ"},
	       // Not autorized {"CHGMQMSVC","CHGMQMSVC"},
	       {"CHGMSGD","CHGMSGD"},
	       {"CHGMSGF","CHGMSGF"},
	       {"CHGMSGQ","CHGMSGQ"},
	       {"CHGNCK","CHGNCK"},
	       {"CHGNFYJS","CHGNFYJS"},
	       {"CHGNODGRPA","CHGNODGRPA"},
	       {"CHGNTBD","CHGNTBD"},
	       {"CHGNTPA","CHGNTPA"},
	       {"CHGNWIFR","CHGNWIFR"},
	       {"CHGNWSD","CHGNWSD"},
	       {"CHGNWSSTG","CHGNWSSTG"},
	       {"CHGNWSUSRA","CHGNWSUSRA"},
	       {"CHGOBJAUD","CHGOBJAUD"},
	       {"CHGOBJD","CHGOBJD"},
	       {"CHGOBJOWN","CHGOBJOWN"},
	       {"CHGOBJPGP","CHGOBJPGP"},
	       {"CHGOPTVOL","CHGOPTVOL"},
	       {"CHGOSPFA","CHGOSPFA"},
	       {"CHGOSPFARA","CHGOSPFARA"},
	       {"CHGOSPFIFC","CHGOSPFIFC"},
	       {"CHGOSPFLNK","CHGOSPFLNK"},
	       {"CHGOSPFRNG","CHGOSPFRNG"},
	       {"CHGOUTQ","CHGOUTQ"},
	       {"CHGOWN","CHGOWN"},
	       {"CHGPCOPRF","CHGPCOPRF"},
	       {"CHGPDGPRF","CHGPDGPRF"},
	       {"CHGPDMDFT","CHGPDMDFT"},
	       {"CHGPF","CHGPF"},
	       {"CHGPFCST","CHGPFCST"},
	       {"CHGPFM","CHGPFM"},
	       {"CHGPFTRG","CHGPFTRG"},
	       {"CHGPGM","CHGPGM"},
	       {"CHGPGMVAR","CHGPGMVAR"},
	       {"CHGPGP","CHGPGP"},
	       {"CHGPGRJS","CHGPGRJS"},
	       {"CHGPJ","CHGPJ"},
	       {"CHGPJE","CHGPJE"},
	       {"CHGPOPA","CHGPOPA"},
	       {"CHGPRBACNE","CHGPRBACNE"},
	       {"CHGPRBSLTE","CHGPRBSLTE"},
	       {"CHGPRF","CHGPRF"},
	       {"CHGPRTF","CHGPRTF"},
	       {"CHGPRXCMD","CHGPRXCMD"},
	       {"CHGPSFCFG","CHGPSFCFG"},
	       {"CHGPWD","CHGPWD"},
	       {"CHGPWRSCD","CHGPWRSCD"},
	       {"CHGPWRSCDE","CHGPWRSCDE"},
	       {"CHGQRYA","CHGQRYA"},
	       {"CHGRDBDIRE","CHGRDBDIRE"},
	       {"CHGRIPA","CHGRIPA"},
	       {"CHGRIPFLT","CHGRIPFLT"},
	       {"CHGRIPIFC","CHGRIPIFC"},
	       {"CHGRJECMNE","CHGRJECMNE"},
	       {"CHGRJERDRE","CHGRJERDRE"},
	       {"CHGRJEWTRE","CHGRJEWTRE"},
	       {"CHGRMTJRN","CHGRMTJRN"},
	       {"CHGRPYLE","CHGRPYLE"},
	       {"CHGRTDA","CHGRTDA"},
	       {"CHGRTGE","CHGRTGE"},
	       {"CHGRWSPWD","CHGRWSPWD"},
	       {"CHGRXCA","CHGRXCA"},
	       {"CHGSAVF","CHGSAVF"},
	       {"CHGSBSD","CHGSBSD"},
	       {"CHGSCDBRM","CHGSCDBRM"},
	       {"CHGSCHIDX","CHGSCHIDX"},
	       {"CHGSECA","CHGSECA"},
	       {"CHGSHRPOOL","CHGSHRPOOL"},
	       {"CHGSMTPA","CHGSMTPA"},
	       {"CHGSNMPA","CHGSNMPA"},
	       {"CHGSPLFA","CHGSPLFA"},
	       {"CHGSRCPF","CHGSRCPF"},
	       {"CHGSRVCFG","CHGSRVCFG"},
	       {"CHGSRVPGM","CHGSRVPGM"},
	       {"CHGSSND","CHGSSND"},
	       {"CHGSSNMAX","CHGSSNMAX"},
	       {"CHGSVRAUTE","CHGSVRAUTE"},
	       {"CHGSYSDIRA","CHGSYSDIRA"},
	       {"CHGSYSVAL","CHGSYSVAL"},
	       {"CHGS36","CHGS36"},
	       {"CHGS36A","CHGS36A"},
	       {"CHGS36MSGL","CHGS36MSGL"},
	       {"CHGS36PGMA","CHGS36PGMA"},
	       {"CHGS36PRCA","CHGS36PRCA"},
	       {"CHGS36SRCA","CHGS36SRCA"},
	       {"CHGTAPCTG","CHGTAPCTG"},
	       {"CHGTAPF","CHGTAPF"},
	       {"CHGTCPA","CHGTCPA"},
	       {"CHGTCPDMN","CHGTCPDMN"},
	       {"CHGTCPHTE","CHGTCPHTE"},
	       {"CHGTCPIFC","CHGTCPIFC"},
	       {"CHGTCPRTE","CHGTCPRTE"},
	       {"CHGTCPSVR","CHGTCPSVR"},
	       {"CHGTEFE","CHGTEFE"},
	       {"CHGTELNA","CHGTELNA"},
	       {"CHGTFTPA","CHGTFTPA"},
	       {"CHGTIMZON","CHGTIMZON"},
	       {"CHGUSRAUD","CHGUSRAUD"},
	       {"CHGUSRPRF","CHGUSRPRF"},
	       {"CHGUSRPRTI","CHGUSRPRTI"},
	       {"CHGUSRTRC","CHGUSRTRC"},
	       {"CHGVAR","CHGVAR"},
	       {"CHGVFYLIST","CHGVFYLIST"},
	       {"CHGVTMAP","CHGVTMAP"},
	       {"CHGWSE","CHGWSE"},
	       {"CHGWTR","CHGWTR"},
	       {"CHGXMTLVL","CHGXMTLVL"},
	       {"CHKBLDJOB","CHKBLDJOB"},
	       {"CHKBLDSVR","CHKBLDSVR"},
	       {"CHKDKT","CHKDKT"},
	       {"CHKDLO","CHKDLO"},
	       {"CHKDNSCFG","CHKDNSCFG"},
	       {"CHKDNSZNE","CHKDNSZNE"},
	       {"CHKEXPBRM","CHKEXPBRM"},
	       // {"CHKFAXSTS","CHKFAXSTS"},
	       {"CHKIGCTBL","CHKIGCTBL"},
	       {"CHKIN","CHKIN"},
	       {"CHKOBJ","CHKOBJ"},
	       {"CHKOBJITG","CHKOBJITG"},
	       {"CHKOPTVOL","CHKOPTVOL"},
	       {"CHKOUT","CHKOUT"},
	       {"CHKPWD","CHKPWD"},
	       {"CHKRCDLCK","CHKRCDLCK"},
	       {"CHKTAP","CHKTAP"},
	       {"CHKVFYLIST","CHKVFYLIST"},
	       {"CLOF","CLOF"},
	       {"CLOSE","CLOSE"},
	       {"CLRBPR","CLRBPR"},
	       {"CLRDKT","CLRDKT"},
	       {"CLRJOBQ","CLRJOBQ"},
	       {"CLRLIB","CLRLIB"},
	       // Not Authorized {"CLRMQMBRK","CLRMQMBRK"},
	       // Not Authorized {"CLRMQMQ","CLRMQMQ"},
	       {"CLRMSGQ","CLRMSGQ"},
	       {"CLROUTQ","CLROUTQ"},
	       {"CLRPFM","CLRPFM"},
	       {"CLRPOOL","CLRPOOL"},
	       {"CLRSAVF","CLRSAVF"},
	       {"CLRSVRSEC","CLRSVRSEC"},
	       {"CLRTRCDTA","CLRTRCDTA"},
	       {"CMD","CMD"},
	       {"CMPJRNIMG","CMPJRNIMG"},
	       {"CMPPFM","CMPPFM"},
	       {"CNLRJERDR","CNLRJERDR"},
	       {"CNLRJEWTR","CNLRJEWTR"},
	       {"COMMIT","COMMIT"},
	       {"COPY","COPY"},
	       {"COPYRIGHT","COPYRIGHT"},
	       {"CPROBJ","CPROBJ"},
	       {"CPY","CPY"},
	       {"CPYAUDJRNE","CPYAUDJRNE"},
	       {"CPYCFGL","CPYCFGL"},
	       {"CPYDOC","CPYDOC"},
	       {"CPYF","CPYF"},
	       // Not Authorized {"CPYFCNARA","CPYFCNARA"},
	       {"CPYFRMDIR","CPYFRMDIR"},
	       {"CPYFRMDKT","CPYFRMDKT"},
	       {"CPYFRMIMPF","CPYFRMIMPF"},
	       {"CPYFRMPCD","CPYFRMPCD"},
	       {"CPYFRMQRYF","CPYFRMQRYF"},
	       {"CPYFRMSTMF","CPYFRMSTMF"},
	       {"CPYFRMTAP","CPYFRMTAP"},
	       // Not Authorized {"CPYGPHFMT","CPYGPHFMT"},
	       // Not Authorized {"CPYGPHPKG","CPYGPHPKG"},
	       {"CPYIGCSRT","CPYIGCSRT"},
	       {"CPYJOBJS","CPYJOBJS"},
	       {"CPYLIB","CPYLIB"},
	       {"CPYMEDIBRM","CPYMEDIBRM"},
	       // Not Authorized {"CPYMQMAUTI","CPYMQMAUTI"},
	       // Not Authorized {"CPYMQMCHL","CPYMQMCHL"},
	       // Not Authorized {"CPYMQMLSR","CPYMQMLSR"},
	       // Not Authorized {"CPYMQMNL","CPYMQMNL"},
	       // Not Authorized {"CPYMQMPRC","CPYMQMPRC"},
	       // Not Authorized {"CPYMQMQ","CPYMQMQ"},
	       // Not Authorized {"CPYMQMSVC","CPYMQMSVC"},
	       {"CPYOPT","CPYOPT"},
	       // Not Authorized {"CPYPFRDTA","CPYPFRDTA"},
	       {"CPYSPLF","CPYSPLF"},
	       {"CPYSRCF","CPYSRCF"},
	       {"CPYTCPHT","CPYTCPHT"},
	       {"CPYTEF","CPYTEF"},
	       {"CPYTEFE","CPYTEFE"},
	       {"CPYTODIR","CPYTODIR"},
	       {"CPYTODKT","CPYTODKT"},
	       {"CPYTOIMPF","CPYTOIMPF"},
	       {"CPYTOPCD","CPYTOPCD"},
	       {"CPYTOSTMF","CPYTOSTMF"},
	       {"CPYTOTAP","CPYTOTAP"},
	       {"CRTAFPDTA","CRTAFPDTA"},
	       {"CRTALRTBL","CRTALRTBL"},
	       {"CRTAUTL","CRTAUTL"},
	       {"CRTBLDEVT","CRTBLDEVT"},
	       {"CRTBNDC","CRTBNDC"},
	       {"CRTBNDCBL","CRTBNDCBL"},
	       {"CRTBNDCL","CRTBNDCL"},
	       {"CRTBNDCPP","CRTBNDCPP"},
	       {"CRTBNDDIR","CRTBNDDIR"},
	       {"CRTBNDRPG","CRTBNDRPG"},
	       {"CRTCBLMOD","CRTCBLMOD"},
	       {"CRTCBLPGM","CRTCBLPGM"},
	       {"CRTCFGL","CRTCFGL"},
	       {"CRTCKMKSF","CRTCKMKSF"},
	       {"CRTCLD","CRTCLD"},
	       {"CRTCLMOD","CRTCLMOD"},
	       {"CRTCLPGM","CRTCLPGM"},
	       {"CRTCMD","CRTCMD"},
	       {"CRTCMOD","CRTCMOD"},
	       {"CRTCOSD","CRTCOSD"},
	       {"CRTCPPMOD","CRTCPPMOD"},
	       {"CRTCRQD","CRTCRQD"},
	       {"CRTCSI","CRTCSI"},
	       {"CRTCTLAPPC","CRTCTLAPPC"},
	       {"CRTCTLASC","CRTCTLASC"},
	       {"CRTCTLBSC","CRTCTLBSC"},
	       {"CRTCTLFNC","CRTCTLFNC"},
	       {"CRTCTLHOST","CRTCTLHOST"},
	       {"CRTCTLLWS","CRTCTLLWS"},
	       {"CRTCTLNET","CRTCTLNET"},
	       {"CRTCTLRTL","CRTCTLRTL"},
	       {"CRTCTLRWS","CRTCTLRWS"},
	       {"CRTCTLTAP","CRTCTLTAP"},
	       {"CRTCTLVWS","CRTCTLVWS"},
	       {"CRTDDMF","CRTDDMF"},
	       {"CRTDEVAPPC","CRTDEVAPPC"},
	       {"CRTDEVASC","CRTDEVASC"},
	       {"CRTDEVASP","CRTDEVASP"},
	       {"CRTDEVBSC","CRTDEVBSC"},
	       {"CRTDEVCRP","CRTDEVCRP"},
	       {"CRTDEVDKT","CRTDEVDKT"},
	       {"CRTDEVDSP","CRTDEVDSP"},
	       {"CRTDEVFNC","CRTDEVFNC"},
	       {"CRTDEVHOST","CRTDEVHOST"},
	       {"CRTDEVINTR","CRTDEVINTR"},
	       {"CRTDEVMLB","CRTDEVMLB"},
	       {"CRTDEVNET","CRTDEVNET"},
	       {"CRTDEVNWSH","CRTDEVNWSH"},
	       {"CRTDEVOPT","CRTDEVOPT"},
	       {"CRTDEVPRT","CRTDEVPRT"},
	       {"CRTDEVRTL","CRTDEVRTL"},
	       {"CRTDEVSNPT","CRTDEVSNPT"},
	       {"CRTDEVSNUF","CRTDEVSNUF"},
	       {"CRTDEVTAP","CRTDEVTAP"},
	       {"CRTDFUDSPF","CRTDFUDSPF"},
	       {"CRTDIR","CRTDIR"},
	       {"CRTDKTF","CRTDKTF"},
	       {"CRTDOC","CRTDOC"},
	       {"CRTDPRTBL","CRTDPRTBL"},
	       {"CRTDSPF","CRTDSPF"},
	       {"CRTDSTL","CRTDSTL"},
	       {"CRTDTAARA","CRTDTAARA"},
	       {"CRTDTADCT","CRTDTADCT"},
	       {"CRTDTAQ","CRTDTAQ"},
	       {"CRTDUPOBJ","CRTDUPOBJ"},
	       {"CRTEDTD","CRTEDTD"},
	       {"CRTERRRPT","CRTERRRPT"},
	       // {"CRTFAXD","CRTFAXD"},
	       // {"CRTFAXDST","CRTFAXDST"},
	       // {"CRTFAXMLE","CRTFAXMLE"},
	       // {"CRTFAXNOTE","CRTFAXNOTE"},
	       // {"CRTFAXPRF","CRTFAXPRF"},
	       // Not Authorized {"CRTFCNARA","CRTFCNARA"},
	       {"CRTFCT","CRTFCT"},
	       {"CRTFLR","CRTFLR"},
	       {"CRTFNTRSC","CRTFNTRSC"},
	       {"CRTFNTTBL","CRTFNTTBL"},
	       {"CRTFORMDF","CRTFORMDF"},
	       {"CRTFTR","CRTFTR"},
	       // Not Authorized {"CRTGPHFMT","CRTGPHFMT"},
	       // Not Authorized {"CRTGPHPKG","CRTGPHPKG"},
	       {"CRTGSS","CRTGSS"},
	       // Not Authorized {"CRTHSTDTA","CRTHSTDTA"},
	       {"CRTICFF","CRTICFF"},
	       {"CRTIGCDCT","CRTIGCDCT"},
	       {"CRTIMGCLG","CRTIMGCLG"},
	       {"CRTJOBQ","CRTJOBQ"},
	       {"CRTJRN","CRTJRN"},
	       {"CRTJRNRCV","CRTJRNRCV"},
	       {"CRTJVAPGM","CRTJVAPGM"},
	       {"CRTLF","CRTLF"},
	       {"CRTLIB","CRTLIB"},
	       {"CRTLINASC","CRTLINASC"},
	       {"CRTLINBSC","CRTLINBSC"},
	       {"CRTLINDDI","CRTLINDDI"},
	       {"CRTLINETH","CRTLINETH"},
	       // {"CRTLINFAX","CRTLINFAX"},
	       {"CRTLINFR","CRTLINFR"},
	       {"CRTLINPPP","CRTLINPPP"},
	       {"CRTLINSDLC","CRTLINSDLC"},
	       {"CRTLINTDLC","CRTLINTDLC"},
	       {"CRTLINTRN","CRTLINTRN"},
	       {"CRTLINWLS","CRTLINWLS"},
	       {"CRTLINX25","CRTLINX25"},
	       {"CRTLOCALE","CRTLOCALE"},
	       {"CRTMNU","CRTMNU"},
	       {"CRTMODD","CRTMODD"},
	       // Not Authorized {"CRTMQM","CRTMQM"},
	       // Not Authorized {"CRTMQMAUTI","CRTMQMAUTI"},
	       // Not Authorized {"CRTMQMCHL","CRTMQMCHL"},
	       // Not Authorized {"CRTMQMLSR","CRTMQMLSR"},
	       // Not Authorized {"CRTMQMNL","CRTMQMNL"},
	       // Not Authorized {"CRTMQMPRC","CRTMQMPRC"},
	       // Not Authorized {"CRTMQMQ","CRTMQMQ"},
	       // Not Authorized {"CRTMQMSVC","CRTMQMSVC"},
	       {"CRTMSGF","CRTMSGF"},
	       {"CRTMSGFMNU","CRTMSGFMNU"},
	       {"CRTMSGQ","CRTMSGQ"},
	       {"CRTNODGRP","CRTNODGRP"},
	       {"CRTNODL","CRTNODL"},
	       {"CRTNTBD","CRTNTBD"},
	       {"CRTNWIFR","CRTNWIFR"},
	       {"CRTNWSD","CRTNWSD"},
	       {"CRTNWSSTG","CRTNWSSTG"},
	       {"CRTOBJLIST","CRTOBJLIST"},
	       {"CRTOUTQ","CRTOUTQ"},
	       {"CRTOVL","CRTOVL"},
	       {"CRTPAGDFN","CRTPAGDFN"},
	       {"CRTPAGSEG","CRTPAGSEG"},
	       {"CRTPDFMAP","CRTPDFMAP"},
	       {"CRTPDG","CRTPDG"},
	       {"CRTPF","CRTPF"},
	       {"CRTPGM","CRTPGM"},
	       {"CRTPKGF","CRTPKGF"},
	       {"CRTPLIPGM","CRTPLIPGM"},
	       {"CRTPNLGRP","CRTPNLGRP"},
	       {"CRTPRDBPR","CRTPRDBPR"},
	       {"CRTPRTF","CRTPRTF"},
	       {"CRTPRXCMD","CRTPRXCMD"},
	       {"CRTPSFCFG","CRTPSFCFG"},
	       {"CRTQMFORM","CRTQMFORM"},
	       {"CRTQMQRY","CRTQMQRY"},
	       {"CRTRJEBSCF","CRTRJEBSCF"},
	       {"CRTRJECFG","CRTRJECFG"},
	       {"CRTRJECMNF","CRTRJECMNF"},
	       {"CRTRNDCCFG","CRTRNDCCFG"},
	       {"CRTRPGMOD","CRTRPGMOD"},
	       {"CRTRPGPGM","CRTRPGPGM"},
	       {"CRTRPTPGM","CRTRPTPGM"},
	       {"CRTSAVF","CRTSAVF"},
	       {"CRTSBOM","CRTSBOM"},
	       {"CRTSCHIDX","CRTSCHIDX"},
	       {"CRTSPADCT","CRTSPADCT"},
	       {"CRTSQLCBL","CRTSQLCBL"},
	       {"CRTSQLCBLI","CRTSQLCBLI"},
	       {"CRTSQLCI","CRTSQLCI"},
	       {"CRTSQLCPPI","CRTSQLCPPI"},
	       {"CRTSQLPKG","CRTSQLPKG"},
	       {"CRTSQLPLI","CRTSQLPLI"},
	       {"CRTSQLRPG","CRTSQLRPG"},
	       {"CRTSQLRPGI","CRTSQLRPGI"},
	       {"CRTSRCPF","CRTSRCPF"},
	       {"CRTSRVCFG","CRTSRVCFG"},
	       {"CRTSRVPGM","CRTSRVPGM"},
	       {"CRTSSND","CRTSSND"},
	       {"CRTS36CBL","CRTS36CBL"},
	       {"CRTS36DSPF","CRTS36DSPF"},
	       {"CRTS36MNU","CRTS36MNU"},
	       {"CRTS36MSGF","CRTS36MSGF"},
	       {"CRTS36RPG","CRTS36RPG"},
	       {"CRTS36RPGR","CRTS36RPGR"},
	       {"CRTS36RPT","CRTS36RPT"},
	       {"CRTTAPCGY","CRTTAPCGY"},
	       {"CRTTAPF","CRTTAPF"},
	       {"CRTTBL","CRTTBL"},
	       {"CRTTEF","CRTTEF"},
	       {"CRTTIMZON","CRTTIMZON"},
	       {"CRTUSRPRF","CRTUSRPRF"},
	       {"CRTVFYLIST","CRTVFYLIST"},
	       {"CRTWSCST","CRTWSCST"},
	       {"CVTCLSRC","CVTCLSRC"},
	       {"CVTDAT","CVTDAT"},
	       {"CVTDLSNAM","CVTDLSNAM"},
	       {"CVTEDU","CVTEDU"},
	       // {"CVTFAXDOC","CVTFAXDOC"},
	       {"CVTIPSIFC","CVTIPSIFC"},
	       {"CVTIPSLOC","CVTIPSLOC"},
	       // Not Authorized {"CVTMQMDTA","CVTMQMDTA"},
	       {"CVTNAMSMTP","CVTNAMSMTP"},
	       {"CVTOPTBKU","CVTOPTBKU"},
	       {"CVTRJEDTA","CVTRJEDTA"},
	       {"CVTRPCSRC","CVTRPCSRC"},
	       {"CVTRPGSRC","CVTRPGSRC"},
	       {"CVTSQLCPP","CVTSQLCPP"},
	       {"CVTTOFLR","CVTTOFLR"},
	       {"CVTUSRCERT","CVTUSRCERT"},
	       {"DATA","DATA"},
	       {"DCL","DCL"},
	       {"DCLF","DCLF"},
	       {"DCLPRCOPT","DCLPRCOPT"},
	       {"DCPOBJ","DCPOBJ"},
	       {"DEL","DEL"},
	       {"DEP","DEP"},
	       {"DIG","DIG"},
	       {"DLCOBJ","DLCOBJ"},
	       {"DLTALR","DLTALR"},
	       {"DLTALRTBL","DLTALRTBL"},
	       {"DLTAUTHLR","DLTAUTHLR"},
	       {"DLTAUTL","DLTAUTL"},
	       {"DLTBLDEVT","DLTBLDEVT"},
	       {"DLTBNDDIR","DLTBNDDIR"},
	       {"DLTCFGL","DLTCFGL"},
	       {"DLTCLD","DLTCLD"},
	       {"DLTCLS","DLTCLS"},
	       {"DLTCMD","DLTCMD"},
	       {"DLTCNNL","DLTCNNL"},
	       {"DLTCOSD","DLTCOSD"},
	       {"DLTCRG","DLTCRG"},
	       {"DLTCRQD","DLTCRQD"},
	       {"DLTCSI","DLTCSI"},
	       {"DLTCTLD","DLTCTLD"},
	       {"DLTDEVD","DLTDEVD"},
	       {"DLTDEVMLB","DLTDEVMLB"},
	       {"DLTDFUPGM","DLTDFUPGM"},
	       {"DLTDKTLBL","DLTDKTLBL"},
	       {"DLTDLO","DLTDLO"},
	       {"DLTDOCL","DLTDOCL"},
	       {"DLTDST","DLTDST"},
	       {"DLTDSTL","DLTDSTL"},
	       {"DLTDTAARA","DLTDTAARA"},
	       {"DLTDTADCT","DLTDTADCT"},
	       {"DLTDTAQ","DLTDTAQ"},
	       {"DLTEDTD","DLTEDTD"},
	       {"DLTF","DLTF"},
	       // {"DLTFAX","DLTFAX"},
	       // {"DLTFAXD","DLTFAXD"},
	       // {"DLTFAXF","DLTFAXF"},
	       // Not Authorized {"DLTFCNARA","DLTFCNARA"},
	       {"DLTFCT","DLTFCT"},
	       {"DLTFNTRSC","DLTFNTRSC"},
	       {"DLTFNTTBL","DLTFNTTBL"},
	       {"DLTFORMDF","DLTFORMDF"},
	       {"DLTFTR","DLTFTR"},
	       // Not Authorized {"DLTGPHFMT","DLTGPHFMT"},
	       // Not Authorized {"DLTGPHPKG","DLTGPHPKG"},
	       {"DLTGSS","DLTGSS"},
	       // Not Authorized {"DLTHSTDTA","DLTHSTDTA"},
	       {"DLTIGCDCT","DLTIGCDCT"},
	       {"DLTIGCSRT","DLTIGCSRT"},
	       {"DLTIGCTBL","DLTIGCTBL"},
	       {"DLTIMGCLG","DLTIMGCLG"},
	       {"DLTIPXD","DLTIPXD"},
	       {"DLTJOBD","DLTJOBD"},
	       {"DLTJOBQ","DLTJOBQ"},
	       {"DLTJRN","DLTJRN"},
	       {"DLTJRNRCV","DLTJRNRCV"},
	       {"DLTJVAPGM","DLTJVAPGM"},
	       {"DLTKRBCCF","DLTKRBCCF"},
	       {"DLTLIB","DLTLIB"},
	       {"DLTLIND","DLTLIND"},
	       // Not Authorized {"DLTLNXSVR","DLTLNXSVR"},
	       {"DLTLOCALE","DLTLOCALE"},
	       {"DLTMEDDFN","DLTMEDDFN"},
	       {"DLTMGTCOL","DLTMGTCOL"},
	       {"DLTMNU","DLTMNU"},
	       {"DLTMOD","DLTMOD"},
	       {"DLTMODD","DLTMODD"},
	       // Not Authorized {"DLTMQM","DLTMQM"},
	       // Not Authorized {"DLTMQMAUTI","DLTMQMAUTI"},
	       // Not Authorized {"DLTMQMBRK","DLTMQMBRK"},
	       // Not Authorized {"DLTMQMCHL","DLTMQMCHL"},
	       // Not Authorized {"DLTMQMLSR","DLTMQMLSR"},
	       // Not Authorized {"DLTMQMNL","DLTMQMNL"},
	       // Not Authorized {"DLTMQMPRC","DLTMQMPRC"},
	       // Not Authorized {"DLTMQMQ","DLTMQMQ"},
	       // Not Authorized {"DLTMQMSVC","DLTMQMSVC"},
	       {"DLTMSGF","DLTMSGF"},
	       {"DLTMSGQ","DLTMSGQ"},
	       {"DLTNETF","DLTNETF"},
	       {"DLTNODGRP","DLTNODGRP"},
	       {"DLTNODL","DLTNODL"},
	       {"DLTNTBD","DLTNTBD"},
	       {"DLTNWID","DLTNWID"},
	       {"DLTNWSD","DLTNWSD"},
	       {"DLTNWSSTG","DLTNWSSTG"},
	       {"DLTOUTQ","DLTOUTQ"},
	       {"DLTOVL","DLTOVL"},
	       {"DLTOVR","DLTOVR"},
	       {"DLTOVRDEVE","DLTOVRDEVE"},
	       {"DLTPAGDFN","DLTPAGDFN"},
	       {"DLTPAGSEG","DLTPAGSEG"},
	       {"DLTPDFMAP","DLTPDFMAP"},
	       {"DLTPDG","DLTPDG"},
	       // Not Authorized {"DLTPFRDTA","DLTPFRDTA"},
	       {"DLTPGM","DLTPGM"},
	       {"DLTPNLGRP","DLTPNLGRP"},
	       {"DLTPSFCFG","DLTPSFCFG"},
	       {"DLTQMFORM","DLTQMFORM"},
	       {"DLTQMQRY","DLTQMQRY"},
	       {"DLTQRY","DLTQRY"},
	       {"DLTRJECFG","DLTRJECFG"},
	       {"DLTSBSD","DLTSBSD"},
	       {"DLTSCHIDX","DLTSCHIDX"},
	       {"DLTSPADCT","DLTSPADCT"},
	       {"DLTSPLF","DLTSPLF"},
	       {"DLTSQLPKG","DLTSQLPKG"},
	       {"DLTSRVCFG","DLTSRVCFG"},
	       {"DLTSRVPGM","DLTSRVPGM"},
	       {"DLTSSND","DLTSSND"},
	       {"DLTTAPCGY","DLTTAPCGY"},
	       {"DLTTBL","DLTTBL"},
	       {"DLTTEF","DLTTEF"},
	       {"DLTTIMZON","DLTTIMZON"},
	       {"DLTUSRIDX","DLTUSRIDX"},
	       {"DLTUSRPRF","DLTUSRPRF"},
	       {"DLTUSRQ","DLTUSRQ"},
	       {"DLTUSRSPC","DLTUSRSPC"},
	       {"DLTUSRTRC","DLTUSRTRC"},
	       {"DLTVFYLIST","DLTVFYLIST"},
	       // Not Authorized {"DLTWNTSVR","DLTWNTSVR"},
	       {"DLTWSCST","DLTWSCST"},
	       {"DLYJOB","DLYJOB"},
	       {"DMPBRM","DMPBRM"},
	       {"DMPCLPGM","DMPCLPGM"},
	       {"DMPCLUTRC","DMPCLUTRC"},
	       {"DMPUSRTRC","DMPUSRTRC"},
	       {"DO","DO"},
	       {"DOFOR","DOFOR"},
	       {"DOUNTIL","DOUNTIL"},
	       {"DOWHILE","DOWHILE"},
	       {"DSCJOB","DSCJOB"},
	       // Not Authorized {"DSCMQM","DSCMQM"},
	       {"DSPACC","DSPACC"},
	       {"DSPACCAUT","DSPACCAUT"},
	       {"DSPACTPJ","DSPACTPJ"},
	       {"DSPAPPNINF","DSPAPPNINF"},
	       {"DSPASPBRM","DSPASPBRM"},
	       {"DSPASPSTS","DSPASPSTS"},
	       {"DSPAUDJRNE","DSPAUDJRNE"},
	       {"DSPAUT","DSPAUT"},
	       {"DSPAUTHLR","DSPAUTHLR"},
	       {"DSPAUTL","DSPAUTL"},
	       {"DSPAUTLDLO","DSPAUTLDLO"},
	       {"DSPAUTLOBJ","DSPAUTLOBJ"},
	       {"DSPAUTUSR","DSPAUTUSR"},
	       {"DSPBCKSTS","DSPBCKSTS"},
	       {"DSPBCKUP","DSPBCKUP"},
	       {"DSPBCKUPL","DSPBCKUPL"},
	       {"DSPBKP","DSPBKP"},
	       {"DSPBKUBRM","DSPBKUBRM"},
	       {"DSPBNDDIR","DSPBNDDIR"},
	       {"DSPCDEFNT","DSPCDEFNT"},
	       {"DSPCFGL","DSPCFGL"},
	       {"DSPCKMKSFE","DSPCKMKSFE"},
	       {"DSPCLS","DSPCLS"},
	       {"DSPCMD","DSPCMD"},
	       {"DSPCNNL","DSPCNNL"},
	       {"DSPCNNSTS","DSPCNNSTS"},
	       {"DSPCOSD","DSPCOSD"},
	       {"DSPCPCST","DSPCPCST"},
	       {"DSPCSI","DSPCSI"},
	       {"DSPCTLD","DSPCTLD"},
	       {"DSPCURDIR","DSPCURDIR"},
	       {"DSPDBG","DSPDBG"},
	       {"DSPDBGWCH","DSPDBGWCH"},
	       {"DSPDBR","DSPDBR"},
	       {"DSPDDMF","DSPDDMF"},
	       {"DSPDEVD","DSPDEVD"},
	       {"DSPDIRE","DSPDIRE"},
	       {"DSPDKT","DSPDKT"},
	       {"DSPDLFA","DSPDLFA"},
	       {"DSPDLOAUD","DSPDLOAUD"},
	       {"DSPDLOAUT","DSPDLOAUT"},
	       {"DSPDLONAM","DSPDLONAM"},
	       {"DSPDOC","DSPDOC"},
	       {"DSPDSTL","DSPDSTL"},
	       {"DSPDSTSRV","DSPDSTSRV"},
	       {"DSPDTA","DSPDTA"},
	       {"DSPDTAARA","DSPDTAARA"},
	       {"DSPDTADCT","DSPDTADCT"},
	       {"DSPDUPBRM","DSPDUPBRM"},
	       {"DSPEDTD","DSPEDTD"},
	       {"DSPEWCBCDE","DSPEWCBCDE"},
	       {"DSPEWCM","DSPEWCM"},
	       {"DSPEWCPTCE","DSPEWCPTCE"},
	       {"DSPEWLM","DSPEWLM"},
	       {"DSPF","DSPF"},
	       // {"DSPFAX","DSPFAX"},
	       {"DSPFCNUSG","DSPFCNUSG"},
	       {"DSPFD","DSPFD"},
	       {"DSPFFD","DSPFFD"},
	       {"DSPFLR","DSPFLR"},
	       {"DSPFMWSTS","DSPFMWSTS"},
	       {"DSPFNTRSCA","DSPFNTRSCA"},
	       {"DSPFNTTBL","DSPFNTTBL"},
	       {"DSPHDWRSC","DSPHDWRSC"},
	       {"DSPHFS","DSPHFS"},
	       {"DSPHLPDOC","DSPHLPDOC"},
	       // Not Authorized {"DSPHSTGPH","DSPHSTGPH"},
	       {"DSPHSTJS","DSPHSTJS"},
	       {"DSPIGCDCT","DSPIGCDCT"},
	       {"DSPIPLA","DSPIPLA"},
	       {"DSPIPXD","DSPIPXD"},
	       {"DSPJOB","DSPJOB"},
	       {"DSPJOBD","DSPJOBD"},
	       {"DSPJOBJS","DSPJOBJS"},
	       {"DSPJOBLOG","DSPJOBLOG"},
	       {"DSPJOBTBL","DSPJOBTBL"},
	       {"DSPJRN","DSPJRN"},
	       {"DSPJRNRCVA","DSPJRNRCVA"},
	       {"DSPJVAPGM","DSPJVAPGM"},
	       {"DSPJVMJOB","DSPJVMJOB"},
	       {"DSPKBDMAP","DSPKBDMAP"},
	       {"DSPKRBCCF","DSPKRBCCF"},
	       {"DSPKRBKTE","DSPKRBKTE"},
	       {"DSPLANADPP","DSPLANADPP"},
	       {"DSPLANMLB","DSPLANMLB"},
	       {"DSPLANSTS","DSPLANSTS"},
	       {"DSPLIB","DSPLIB"},
	       {"DSPLIBD","DSPLIBD"},
	       {"DSPLIBL","DSPLIBL"},
	       {"DSPLIND","DSPLIND"},
	       {"DSPLNK","DSPLNK"},
	       {"DSPLOG","DSPLOG"},
	       {"DSPLOGBRM","DSPLOGBRM"},
	       {"DSPLOGJS","DSPLOGJS"},
	       {"DSPMFSINF","DSPMFSINF"},
	       {"DSPMNUA","DSPMNUA"},
	       {"DSPMOD","DSPMOD"},
	       {"DSPMODD","DSPMODD"},
	       {"DSPMODSRC","DSPMODSRC"},
	       {"DSPMODSTS","DSPMODSTS"},
	       // Not Authorized {"DSPMQM","DSPMQM"},
	       // Not Authorized {"DSPMQMAUT","DSPMQMAUT"},
	       // Not Authorized {"DSPMQMAUTI","DSPMQMAUTI"},
	       // Not Authorized {"DSPMQMBRK","DSPMQMBRK"},
	       // Not Authorized {"DSPMQMCHL","DSPMQMCHL"},
	       // Not Authorized {"DSPMQMCSVR","DSPMQMCSVR"},
	       // Not Authorized {"DSPMQMLSR","DSPMQMLSR"},
	       // Not Authorized {"DSPMQMNL","DSPMQMNL"},
	       // Not Authorized {"DSPMQMOBJN","DSPMQMOBJN"},
	       // Not Authorized {"DSPMQMPRC","DSPMQMPRC"},
	       // Not Authorized {"DSPMQMQ","DSPMQMQ"},
	       // Not Authorized {"DSPMQMRTE","DSPMQMRTE"},
	       // Not Authorized {"DSPMQMSTS","DSPMQMSTS"},
	       // Not Authorized {"DSPMQMSVC","DSPMQMSVC"},
	       // Not Authorized {"DSPMQMVER","DSPMQMVER"},
	       {"DSPMSG","DSPMSG"},
	       {"DSPMSGD","DSPMSGD"},
	       {"DSPNCK","DSPNCK"},
	       {"DSPNETA","DSPNETA"},
	       {"DSPNODGRP","DSPNODGRP"},
	       {"DSPNTBD","DSPNTBD"},
	       {"DSPNWID","DSPNWID"},
	       {"DSPNWSA","DSPNWSA"},
	       {"DSPNWSD","DSPNWSD"},
	       {"DSPNWSSTG","DSPNWSSTG"},
	       {"DSPNWSUSRA","DSPNWSUSRA"},
	       {"DSPOBJAUT","DSPOBJAUT"},
	       {"DSPOBJD","DSPOBJD"},
	       {"DSPOPCLNK","DSPOPCLNK"},
	       {"DSPOPT","DSPOPT"},
	       {"DSPOPTLCK","DSPOPTLCK"},
	       {"DSPOPTSVR","DSPOPTSVR"},
	       {"DSPOSPF","DSPOSPF"},
	       {"DSPOVR","DSPOVR"},
	       {"DSPPDFMAPE","DSPPDFMAPE"},
	       {"DSPPDGPRF","DSPPDGPRF"},
	       {"DSPPFM","DSPPFM"},
	       // Not Authorized {"DSPPFRDTA","DSPPFRDTA"},
	       // Not Authorized {"DSPPFRGPH","DSPPFRGPH"},
	       {"DSPPGM","DSPPGM"},
	       {"DSPPGMADP","DSPPGMADP"},
	       {"DSPPGMREF","DSPPGMREF"},
	       {"DSPPGMVAR","DSPPGMVAR"},
	       {"DSPPRB","DSPPRB"},
	       {"DSPPSFCFG","DSPPSFCFG"},
	       {"DSPPWRSCD","DSPPWRSCD"},
	       {"DSPRCDLCK","DSPRCDLCK"},
	       {"DSPRCYAP","DSPRCYAP"},
	       {"DSPRDBDIRE","DSPRDBDIRE"},
	       {"DSPRIP","DSPRIP"},
	       {"DSPRJECFG","DSPRJECFG"},
	       {"DSPRMTDFN","DSPRMTDFN"},
	       {"DSPSAVF","DSPSAVF"},
	       {"DSPSBSD","DSPSBSD"},
	       {"DSPSECA","DSPSECA"},
	       {"DSPSECAUD","DSPSECAUD"},
	       {"DSPSFWRSC","DSPSFWRSC"},
	       {"DSPSOCSTS","DSPSOCSTS"},
	       {"DSPSPLF","DSPSPLF"},
	       {"DSPSRVA","DSPSRVA"},
	       {"DSPSRVPGM","DSPSRVPGM"},
	       {"DSPSSTUSR","DSPSSTUSR"},
	       {"DSPSVRAUTE","DSPSVRAUTE"},
	       {"DSPSYSSTS","DSPSYSSTS"},
	       {"DSPSYSVAL","DSPSYSVAL"},
	       {"DSPS36","DSPS36"},
	       {"DSPTAP","DSPTAP"},
	       {"DSPTAPCGY","DSPTAPCGY"},
	       {"DSPTAPCTG","DSPTAPCTG"},
	       {"DSPTAPSTS","DSPTAPSTS"},
	       {"DSPTM","DSPTM"},
	       {"DSPTRC","DSPTRC"},
	       {"DSPTRCDTA","DSPTRCDTA"},
	       {"DSPUDFS","DSPUDFS"},
	       {"DSPUSRPMN","DSPUSRPMN"},
	       {"DSPUSRPRF","DSPUSRPRF"},
	       {"DSPUSRPRTI","DSPUSRPRTI"},
	       {"DSPVFYLIST","DSPVFYLIST"},
	       {"DSPVTMAP","DSPVTMAP"},
	       {"DSPWEBQRY","DSPWEBQRY"},
	       {"DSPWSUSR","DSPWSUSR"},
	       {"DUPDKT","DUPDKT"},
	       {"DUPMEDBRM","DUPMEDBRM"},
	       {"DUPOPT","DUPOPT"},
	       {"DUPTAP","DUPTAP"},
	       {"EDTAUTL","EDTAUTL"},
	       {"EDTBCKUPL","EDTBCKUPL"},
	       {"EDTDLOAUT","EDTDLOAUT"},
	       {"EDTDOC","EDTDOC"},
	       {"EDTF","EDTF"},
	       // {"EDTFAXDST","EDTFAXDST"},
	       // {"EDTFAXPRF","EDTFAXPRF"},
	       {"EDTIGCDCT","EDTIGCDCT"},
	       {"EDTLIBL","EDTLIBL"},
	       {"EDTOBJAUT","EDTOBJAUT"},
	       {"EDTS36PGMA","EDTS36PGMA"},
	       {"EDTS36PRCA","EDTS36PRCA"},
	       {"EDTS36SRCA","EDTS36SRCA"},
	       {"EDTWSOAUT","EDTWSOAUT"},
	       {"EJTEMLOUT","EJTEMLOUT"},
	       {"ELEM","ELEM"},
	       {"ELSE","ELSE"},
	       {"EMLPRTKEY","EMLPRTKEY"},
	       {"ENDAGTSRV","ENDAGTSRV"},
	       {"ENDBCHJOB","ENDBCHJOB"},
	       {"ENDBLDIMPT","ENDBLDIMPT"},
	       {"ENDCBLDBG","ENDCBLDBG"},
	       {"ENDCLNUP","ENDCLNUP"},
	       {"ENDCMTCTL","ENDCMTCTL"},
	       {"ENDCPYSCN","ENDCPYSCN"},
	       {"ENDCTLRCY","ENDCTLRCY"},
	       {"ENDDBG","ENDDBG"},
	       {"ENDDBMON","ENDDBMON"},
	       {"ENDDEVRCY","ENDDEVRCY"},
	       {"ENDDIRSHD","ENDDIRSHD"},
	       {"ENDDO","ENDDO"},
	       {"ENDDPRAPY","ENDDPRAPY"},
	       {"ENDDPRCAP","ENDDPRCAP"},
	       {"ENDEPMENV","ENDEPMENV"},
	       {"ENDFAXSPT","ENDFAXSPT"},
	       // Not Authorized {"ENDFNTDWN","ENDFNTDWN"},
	       {"ENDGRPJOB","ENDGRPJOB"},
	       {"ENDHTTPCRL","ENDHTTPCRL"},
	       {"ENDINP","ENDINP"},
	       {"ENDISDB","ENDISDB"},
	       {"ENDJOB","ENDJOB"},
	       // Not Authorized {"ENDJOBTRC","ENDJOBTRC"},
	       {"ENDJRN","ENDJRN"},
	       {"ENDJRNAP","ENDJRNAP"},
	       {"ENDJRNLIB","ENDJRNLIB"},
	       {"ENDJRNOBJ","ENDJRNOBJ"},
	       {"ENDJRNPF","ENDJRNPF"},
	       {"ENDJS","ENDJS"},
	       {"ENDLINRCY","ENDLINRCY"},
	       {"ENDLOGSVR","ENDLOGSVR"},
	       {"ENDMOD","ENDMOD"},
	       // Not Authorized {"ENDMQM","ENDMQM"},
	       // Not Authorized {"ENDMQMBRK","ENDMQMBRK"},
	       // Not Authorized {"ENDMQMCHL","ENDMQMCHL"},
	       // Not Authorized {"ENDMQMCONN","ENDMQMCONN"},
	       // Not Authorized {"ENDMQMCSVR","ENDMQMCSVR"},
	       // Not Authorized {"ENDMQMLSR","ENDMQMLSR"},
	       // Not Authorized {"ENDMQMSVC","ENDMQMSVC"},
	       {"ENDNWIRCY","ENDNWIRCY"},
	       {"ENDPASTHR","ENDPASTHR"},
	       {"ENDPGM","ENDPGM"},
	       {"ENDPGMEXP","ENDPGMEXP"},
	       {"ENDPJ","ENDPJ"},
	       {"ENDPRTEML","ENDPRTEML"},
	       {"ENDRCV","ENDRCV"},
	       {"ENDRDR","ENDRDR"},
	       {"ENDREPBPR","ENDREPBPR"},
	       {"ENDRJESSN","ENDRJESSN"},
	       {"ENDRQS","ENDRQS"},
	       {"ENDSBS","ENDSBS"},
	       {"ENDSELECT","ENDSELECT"},
	       {"ENDSUBR","ENDSUBR"},
	       {"ENDSYS","ENDSYS"},
	       {"ENDS36","ENDS36"},
	       {"ENDTFMMGR","ENDTFMMGR"},
	       {"ENDTIESSN","ENDTIESSN"},
	       {"ENDVFYMON","ENDVFYMON"},
	       // Not Authorized {"ENDWEBQRY","ENDWEBQRY"},
	       {"ENDWTR","ENDWTR"},
	       {"EOF","EOF"},
	       {"ERASE","ERASE"},
	       {"EXPORT","EXPORT"},
	       {"EXTMEDIBRM","EXTMEDIBRM"},
	       {"EXTPGMINF","EXTPGMINF"},
	       {"FILDOC","FILDOC"},
	       {"FILFAX","FILFAX"},
	       {"FMTDTA","FMTDTA"},
	       {"FNDSTRPDM","FNDSTRPDM"},
	       {"FTP","FTP"},
	       {"GENCAT","GENCAT"},
	       {"GENCKMKSFE","GENCKMKSFE"},
	       {"GENCMDDOC","GENCMDDOC"},
	       {"GENCSRC","GENCSRC"},
	       {"GENJVMDMP","GENJVMDMP"},
	       {"GETBLDOPTE","GETBLDOPTE"},
	       {"GETTEFE","GETTEFE"},
	       {"GO","GO"},
	       {"GOTO","GOTO"},
	       // Not Authorized {"GRTDPRAUT","GRTDPRAUT"},
	       {"GRTDSTAUT","GRTDSTAUT"},
	       {"GRTMLEAUT","GRTMLEAUT"},
	       // Not Authorized {"GRTMQMAUT","GRTMQMAUT"},
	       {"GRTOBJAUT","GRTOBJAUT"},
	       {"GRTUSRAUT","GRTUSRAUT"},
	       {"GRTUSRPMN","GRTUSRPMN"},
	       {"GRTWSOAUT","GRTWSOAUT"},
	       {"HLDJOB","HLDJOB"},
	       {"HLDJOBJS","HLDJOBJS"},
	       {"HLDJOBQ","HLDJOBQ"},
	       {"HLDJOBSCDE","HLDJOBSCDE"},
	       {"HLDOUTQ","HLDOUTQ"},
	       {"HLDRDR","HLDRDR"},
	       {"HLDSPLF","HLDSPLF"},
	       {"HLDWTR","HLDWTR"},
	       {"HOST","HOST"},
	       {"ICLEAR","ICLEAR"},
	       {"ICLRDIR","ICLRDIR"},
	       {"IF","IF"},
	       {"INCLUDE","INCLUDE"},
	       // Not Authorized {"INSLNXSVR","INSLNXSVR"},
	       // Not Authorized {"INSWNTSVR","INSWNTSVR"},
	       {"INZBRM","INZBRM"},
	       {"INZDKT","INZDKT"},
	       {"INZDLFM","INZDLFM"},
	       {"INZDPRCAP","INZDPRCAP"},
	       {"INZMEDBRM","INZMEDBRM"},
	       {"INZOPT","INZOPT"},
	       {"INZPCS","INZPCS"},
	       {"INZPFM","INZPFM"},
	       {"INZTAP","INZTAP"},
	       {"ISAVEDIA","ISAVEDIA"},
	       {"ISHOW","ISHOW"},
	       {"ISHOWLOG","ISHOWLOG"},
	       {"ISTART","ISTART"},
	       {"ISTOP","ISTOP"},
	       {"ITERATE","ITERATE"},
	       {"ITRCOFF","ITRCOFF"},
	       {"ITRCON","ITRCON"},
	       {"JAVA","JAVA"},
	       {"LEAVE","LEAVE"},
	       {"LNKDTADFN","LNKDTADFN"},
	       {"LODIMGCLG","LODIMGCLG"},
	       {"LODIMGCLGE","LODIMGCLGE"},
	       {"LODRUN","LODRUN"},
	       {"LPR","LPR"},
	       {"MD","MD"},
	       {"MGRBRM","MGRBRM"},
	       {"MKDIR","MKDIR"},
	       {"MONMSG","MONMSG"},
	       {"MONSWABRM","MONSWABRM"},
	       {"MOV","MOV"},
	       {"MOVDOC","MOVDOC"},
	       {"MOVE","MOVE"},
	       {"MOVMEDBRM","MOVMEDBRM"},
	       {"MOVOBJ","MOVOBJ"},
	       {"MOVSPLFBRM","MOVSPLFBRM"},
	       {"MRGFORMD","MRGFORMD"},
	       {"MRGMSGCLG","MRGMSGCLG"},
	       {"MRGMSGF","MRGMSGF"},
	       {"MRGPKG","MRGPKG"},
	       {"MRGSRC","MRGSRC"},
	       {"MRGTCPHT","MRGTCPHT"},
	       {"NETSTAT","NETSTAT"},
	       {"NSLOOKUP","NSLOOKUP"},
	       {"NSUPDATE","NSUPDATE"},
	       {"O","O"},
	       {"OPNDBF","OPNDBF"},
	       {"OPNQRYF","OPNQRYF"},
	       {"OTHERWISE","OTHERWISE"},
	       {"OVRDBF","OVRDBF"},
	       {"OVRDKTF","OVRDKTF"},
	       {"OVRDSPF","OVRDSPF"},
	       {"OVRICFDEVE","OVRICFDEVE"},
	       {"OVRICFF","OVRICFF"},
	       {"OVRMSGF","OVRMSGF"},
	       {"OVRPRTF","OVRPRTF"},
	       {"OVRSAVF","OVRSAVF"},
	       {"OVRTAPF","OVRTAPF"},
	       {"PARM","PARM"},
	       {"PGM","PGM"},
	       {"PING","PING"},
	       {"PMLINMON","PMLINMON"},
	       {"PMTCTL","PMTCTL"},
	       // Not Authorized {"PNGMQMCHL","PNGMQMCHL"},
	       {"POSDBF","POSDBF"},
	       // Not Authorized {"PRTACTRPT","PRTACTRPT"},
	       {"PRTADPOBJ","PRTADPOBJ"},
	       {"PRTAFPDTA","PRTAFPDTA"},
	       {"PRTCMDUSG","PRTCMDUSG"},
	       {"PRTCMNSEC","PRTCMNSEC"},
	       // Not Authorized {"PRTCPTRPT","PRTCPTRPT"},
	       {"PRTDEVADR","PRTDEVADR"},
	       {"PRTDOC","PRTDOC"},
	       {"PRTFAX","PRTFAX"},
	       {"PRTFAXCFG","PRTFAXCFG"},
	       {"PRTFAXSTS","PRTFAXSTS"},
	       {"PRTIPSCFG","PRTIPSCFG"},
	       {"PRTJOBDAUT","PRTJOBDAUT"},
	       // Not Authorized {"PRTJOBRPT","PRTJOBRPT"},
	       // Not Authorized {"PRTJOBTRC","PRTJOBTRC"},
	       {"PRTJVMJOB","PRTJVMJOB"},
	       {"PRTLBLBRM","PRTLBLBRM"},
	       // Not Authorized {"PRTLCKRPT","PRTLCKRPT"},
	       {"PRTMEDBRM","PRTMEDBRM"},
	       {"PRTMOVBRM","PRTMOVBRM"},
	       {"PRTOPCACT","PRTOPCACT"},
	       {"PRTOPCJOB","PRTOPCJOB"},
	       // Not Authorized {"PRTPOLRPT","PRTPOLRPT"},
	       {"PRTPUBAUT","PRTPUBAUT"},
	       {"PRTPVTAUT","PRTPVTAUT"},
	       {"PRTQAUT","PRTQAUT"},
	       {"PRTRPTBRM","PRTRPTBRM"},
	       // Not Authorized {"PRTRSCRPT","PRTRSCRPT"},
	       {"PRTSBSDAUT","PRTSBSDAUT"},
	       {"PRTSCDJS","PRTSCDJS"},
	       {"PRTSQLINF","PRTSQLINF"},
	       {"PRTSWL","PRTSWL"},
	       // Not Authorized {"PRTSYSRPT","PRTSYSRPT"},
	       {"PRTSYSSECA","PRTSYSSECA"},
	       {"PRTTCPPTP","PRTTCPPTP"},
	       // Not Authorized {"PRTTNSRPT","PRTTNSRPT"},
	       // Not Authorized {"PRTTRCRPT","PRTTRCRPT"},
	       {"PRTTRGPGM","PRTTRGPGM"},
	       {"PRTUSROBJ","PRTUSROBJ"},
	       {"PRTUSRPRF","PRTUSRPRF"},
	       {"QRYDOCLIB","QRYDOCLIB"},
	       {"QRYDST","QRYDST"},
	       {"QRYTIEF","QRYTIEF"},
	       {"QSH","QSH"},
	       {"QUAL","QUAL"},
	       // Not Authorized {"RCDMQMIMG","RCDMQMIMG"},
	       {"RCLACTGRP","RCLACTGRP"},
	       {"RCLDDMCNV","RCLDDMCNV"},
	       {"RCLDLO","RCLDLO"},
	       {"RCLLIB","RCLLIB"},
	       {"RCLLNK","RCLLNK"},
	       {"RCLRSC","RCLRSC"},
	       // Not Authorized {"RCRMQMOBJ","RCRMQMOBJ"},
	       {"RCVDST","RCVDST"},
	       {"RCVF","RCVF"},
	       {"RCVJRNE","RCVJRNE"},
	       {"RCVMSG","RCVMSG"},
	       {"RCVNETF","RCVNETF"},
	       {"RCVTIEF","RCVTIEF"},
	       {"RD","RD"},
	       {"READFILE","READFILE"},
	       {"REN","REN"},
	       {"REPBPR","REPBPR"},
	       {"REPOBJ","REPOBJ"},
	       {"RETURN","RETURN"},
	       // Not Authorized {"RFRMQMAUT","RFRMQMAUT"},
	       // Not Authorized {"RFRMQMCL","RFRMQMCL"},
	       {"RGZDLO","RGZDLO"},
	       {"RGZPFM","RGZPFM"},
	       {"RLSJOB","RLSJOB"},
	       {"RLSJOBJS","RLSJOBJS"},
	       {"RLSJOBQ","RLSJOBQ"},
	       {"RLSJOBSCDE","RLSJOBSCDE"},
	       {"RLSOUTQ","RLSOUTQ"},
	       {"RLSRDR","RLSRDR"},
	       {"RLSSPLF","RLSSPLF"},
	       {"RLSWTR","RLSWTR"},
	       {"RMDIR","RMDIR"},
	       {"RMVAJE","RMVAJE"},
	       {"RMVALRD","RMVALRD"},
	       {"RMVAUTLE","RMVAUTLE"},
	       {"RMVBKP","RMVBKP"},
	       {"RMVBLDOPTE","RMVBLDOPTE"},
	       {"RMVBNDDIRE","RMVBNDDIRE"},
	       {"RMVBUILDER","RMVBUILDER"},
	       {"RMVCFGLE","RMVCFGLE"},
	       {"RMVCKMKSFE","RMVCKMKSFE"},
	       {"RMVCMNE","RMVCMNE"},
	       {"RMVCOMSNMP","RMVCOMSNMP"},
	       {"RMVDIR","RMVDIR"},
	       {"RMVDIRE","RMVDIRE"},
	       {"RMVDIRSHD","RMVDIRSHD"},
	       {"RMVDLOAUT","RMVDLOAUT"},
	       {"RMVDPRREG","RMVDPRREG"},
	       {"RMVDPRSUB","RMVDPRSUB"},
	       {"RMVDPRSUBM","RMVDPRSUBM"},
	       {"RMVDSTLE","RMVDSTLE"},
	       {"RMVEMLCFGE","RMVEMLCFGE"},
	       {"RMVENVVAR","RMVENVVAR"},
	       {"RMVEWCBCDE","RMVEWCBCDE"},
	       {"RMVEWCPTCE","RMVEWCPTCE"},
	       {"RMVFAXCRD","RMVFAXCRD"},
	       {"RMVFAXDLE","RMVFAXDLE"},
	       {"RMVFAXDST","RMVFAXDST"},
	       {"RMVFAXMLE","RMVFAXMLE"},
	       {"RMVFCTE","RMVFCTE"},
	       {"RMVFNTTBLE","RMVFNTTBLE"},
	       {"RMVFTRACNE","RMVFTRACNE"},
	       {"RMVFTRSLTE","RMVFTRSLTE"},
	       {"RMVHSTJS","RMVHSTJS"},
	       {"RMVICFDEVE","RMVICFDEVE"},
	       {"RMVIMGCLGE","RMVIMGCLGE"},
	       {"RMVIPSIFC","RMVIPSIFC"},
	       {"RMVIPSLOC","RMVIPSLOC"},
	       {"RMVIPSRTE","RMVIPSRTE"},
	       {"RMVJOBJS","RMVJOBJS"},
	       {"RMVJOBQE","RMVJOBQE"},
	       {"RMVJOBSCDE","RMVJOBSCDE"},
	       {"RMVKRBKTE","RMVKRBKTE"},
	       {"RMVLANADPI","RMVLANADPI"},
	       {"RMVLIBLE","RMVLIBLE"},
	       {"RMVLNK","RMVLNK"},
	       {"RMVLOGEBRM","RMVLOGEBRM"},
	       {"RMVLOGEJS","RMVLOGEJS"},
	       {"RMVM","RMVM"},
	       {"RMVMEDBRM","RMVMEDBRM"},
	       {"RMVMEDIBRM","RMVMEDIBRM"},
	       {"RMVMSG","RMVMSG"},
	       {"RMVMSGD","RMVMSGD"},
	       {"RMVNCK","RMVNCK"},
	       {"RMVNETTBLE","RMVNETTBLE"},
	       {"RMVNODLE","RMVNODLE"},
	       {"RMVNWSSTGL","RMVNWSSTGL"},
	       {"RMVOSPFARA","RMVOSPFARA"},
	       {"RMVOSPFIFC","RMVOSPFIFC"},
	       {"RMVOSPFLNK","RMVOSPFLNK"},
	       {"RMVOSPFRNG","RMVOSPFRNG"},
	       {"RMVPCLTBLE","RMVPCLTBLE"},
	       {"RMVPFCST","RMVPFCST"},
	       {"RMVPFTRG","RMVPFTRG"},
	       {"RMVPGM","RMVPGM"},
	       {"RMVPJE","RMVPJE"},
	       {"RMVPRDBPR","RMVPRDBPR"},
	       {"RMVRDBDIRE","RMVRDBDIRE"},
	       {"RMVREXBUF","RMVREXBUF"},
	       {"RMVRIPACP","RMVRIPACP"},
	       {"RMVRIPFLT","RMVRIPFLT"},
	       {"RMVRIPIFC","RMVRIPIFC"},
	       {"RMVRIPIGN","RMVRIPIGN"},
	       {"RMVRJECMNE","RMVRJECMNE"},
	       {"RMVRJERDRE","RMVRJERDRE"},
	       {"RMVRJEWTRE","RMVRJEWTRE"},
	       {"RMVRMTJRN","RMVRMTJRN"},
	       {"RMVRPYLE","RMVRPYLE"},
	       {"RMVRTGE","RMVRTGE"},
	       {"RMVSCHIDXE","RMVSCHIDXE"},
	       {"RMVSMTPLE","RMVSMTPLE"},
	       {"RMVSOCE","RMVSOCE"},
	       {"RMVSRVTBLE","RMVSRVTBLE"},
	       {"RMVSVRAUTE","RMVSVRAUTE"},
	       {"RMVTAPCTG","RMVTAPCTG"},
	       {"RMVTCPHTE","RMVTCPHTE"},
	       {"RMVTCPIFC","RMVTCPIFC"},
	       {"RMVTCPPORT","RMVTCPPORT"},
	       {"RMVTCPPTP","RMVTCPPTP"},
	       {"RMVTCPRSI","RMVTCPRSI"},
	       {"RMVTCPRTE","RMVTCPRTE"},
	       {"RMVTCPSVR","RMVTCPSVR"},
	       {"RMVTCPTBL","RMVTCPTBL"},
	       {"RMVTEFE","RMVTEFE"},
	       {"RMVTRC","RMVTRC"},
	       {"RMVWSE","RMVWSE"},
	       {"RNDC","RNDC"},
	       {"RNM","RNM"},
	       {"RNMDIRE","RNMDIRE"},
	       {"RNMDKT","RNMDKT"},
	       {"RNMDLO","RNMDLO"},
	       {"RNMDSTL","RNMDSTL"},
	       {"RNMJOBJS","RNMJOBJS"},
	       {"RNMLANADPI","RNMLANADPI"},
	       {"RNMM","RNMM"},
	       {"RNMNCK","RNMNCK"},
	       {"RNMOBJ","RNMOBJ"},
	       {"RNMTCPHTE","RNMTCPHTE"},
	       {"ROLLBACK","ROLLBACK"},
	       {"RPCGEN","RPCGEN"},
	       {"RPLDOC","RPLDOC"},
	       {"RRTJOB","RRTJOB"},
	       {"RSMBKP","RSMBKP"},
	       {"RSMCTLRCY","RSMCTLRCY"},
	       {"RSMDEVRCY","RSMDEVRCY"},
	       {"RSMHTTPCRL","RSMHTTPCRL"},
	       {"RSMLINRCY","RSMLINRCY"},
	       // Not Authorized {"RSMMQMCLQM","RSMMQMCLQM"},
	       {"RSMNWIRCY","RSMNWIRCY"},
	       {"RSMRTVBRM","RSMRTVBRM"},
	       // Not Authorized {"RSTAUTBRM","RSTAUTBRM"},
	       {"RSTBLDEVT","RSTBLDEVT"},
	       // Not Authorized {"RSTBRM","RSTBRM"},
	       {"RSTBUILDER","RSTBUILDER"},
	       // Not Authorized {"RSTDLOBRM","RSTDLOBRM"},
	       // Not Authorized {"RSTLIBBRM","RSTLIBBRM"},
	       // Not Authorized {"RSTMQMCHL","RSTMQMCHL"},
	       // Not Authorized {"RSTMQMCL","RSTMQMCL"},
	       // Not Authorized {"RSTOBJBRM","RSTOBJBRM"},
	       {"RSTPRDBPR","RSTPRDBPR"},
	       // Not Authorized {"RSVMQMCHL","RSVMQMCHL"},
	       {"RTNSUBR","RTNSUBR"},
	       {"RTVAUTLE","RTVAUTLE"},
	       {"RTVBCKUP","RTVBCKUP"},
	       {"RTVBLDSTS","RTVBLDSTS"},
	       {"RTVBLDTYPE","RTVBLDTYPE"},
	       {"RTVBNDSRC","RTVBNDSRC"},
	       {"RTVCFGSRC","RTVCFGSRC"},
	       {"RTVCFGSTS","RTVCFGSTS"},
	       {"RTVCLDSRC","RTVCLDSRC"},
	       {"RTVCLNUP","RTVCLNUP"},
	       {"RTVCLSRC","RTVCLSRC"},
	       {"RTVCURDIR","RTVCURDIR"},
	       {"RTVDLONAM","RTVDLONAM"},
	       {"RTVDOC","RTVDOC"},
	       {"RTVDTAARA","RTVDTAARA"},
	       {"RTVGRPA","RTVGRPA"},
	       {"RTVIMGCLG","RTVIMGCLG"},
	       {"RTVJOBA","RTVJOBA"},
	       {"RTVJRNE","RTVJRNE"},
	       {"RTVLIBD","RTVLIBD"},
	       {"RTVMBRD","RTVMBRD"},
	       {"RTVMSG","RTVMSG"},
	       {"RTVNETA","RTVNETA"},
	       {"RTVOBJD","RTVOBJD"},
	       {"RTVPDGPRF","RTVPDGPRF"},
	       {"RTVPWRSCDE","RTVPWRSCDE"},
	       {"RTVQMFORM","RTVQMFORM"},
	       {"RTVQMQRY","RTVQMQRY"},
	       {"RTVSWLSRC","RTVSWLSRC"},
	       {"RTVSYSVAL","RTVSYSVAL"},
	       {"RTVS36A","RTVS36A"},
	       {"RTVTBLSRC","RTVTBLSRC"},
	       {"RTVUSRPRF","RTVUSRPRF"},
	       {"RTVUSRPRTI","RTVUSRPRTI"},
	       {"RTVWSCST","RTVWSCST"},
	       {"RUNBCKUP","RUNBCKUP"},
	       {"RUNDNSUPD","RUNDNSUPD"},
	       {"RUNJVA","RUNJVA"},
	       // Not Authorized {"RUNMQSC","RUNMQSC"},
	       {"RUNQRY","RUNQRY"},
	       {"RUNRMTCMD","RUNRMTCMD"},
	       {"RUNRNDCCMD","RUNRNDCCMD"},
	       {"RUNSQLSTM","RUNSQLSTM"},
	       // Not Authorized {"RUNWEBQRY","RUNWEBQRY"},
	       {"RVKACCAUT","RVKACCAUT"},
	       // Not Authorized {"RVKDPRAUT","RVKDPRAUT"},
	       // Not Authorized {"RVKMQMAUT","RVKMQMAUT"},
	       {"RVKOBJAUT","RVKOBJAUT"},
	       {"RVKUSRPMN","RVKUSRPMN"},
	       {"RVKWSOAUT","RVKWSOAUT"},
	       {"SAV","SAV"},
	       {"SAVBLDEVT","SAVBLDEVT"},
	       {"SAVBRM","SAVBRM"},
	       {"SAVBUILDER","SAVBUILDER"},
	       {"SAVCFG","SAVCFG"},
	       {"SAVCHGOBJ","SAVCHGOBJ"},
	       {"SAVDLO","SAVDLO"},
	       {"SAVDLOBRM","SAVDLOBRM"},
	       {"SAVFLRLBRM","SAVFLRLBRM"},
	       {"SAVLIB","SAVLIB"},
	       {"SAVLIBBRM","SAVLIBBRM"},
	       {"SAVMEDIBRM","SAVMEDIBRM"},
	       {"SAVOBJ","SAVOBJ"},
	       {"SAVOBJBRM","SAVOBJBRM"},
	       {"SAVOBJLBRM","SAVOBJLBRM"},
	       {"SAVPRDBPR","SAVPRDBPR"},
	       // Not Authorized {"SAVRST","SAVRST"},
	       // Not Authorized {"SAVRSTCFG","SAVRSTCFG"},
	       // Not Authorized {"SAVRSTCHG","SAVRSTCHG"},
	       // Not Authorized {"SAVRSTDLO","SAVRSTDLO"},
	       // Not Authorized {"SAVRSTLIB","SAVRSTLIB"},
	       // Not Authorized {"SAVRSTOBJ","SAVRSTOBJ"},
	       {"SAVSAVFBRM","SAVSAVFBRM"},
	       {"SAVSAVFDTA","SAVSAVFDTA"},
	       {"SAVSECDTA","SAVSECDTA"},
	       {"SAVSTG","SAVSTG"},
	       {"SAVSYS","SAVSYS"},
	       {"SAVSYSBRM","SAVSYSBRM"},
	       {"SAVSYSINF","SAVSYSINF"},
	       {"SAVS36F","SAVS36F"},
	       {"SAVS36LIBM","SAVS36LIBM"},
	       {"SBMCMDJS","SBMCMDJS"},
	       {"SBMCODEJOB","SBMCODEJOB"},
	       {"SBMDBJOB","SBMDBJOB"},
	       {"SBMDKTJOB","SBMDKTJOB"},
	       {"SBMFAX","SBMFAX"},
	       {"SBMJOB","SBMJOB"},
	       {"SBMJOBJS","SBMJOBJS"},
	       {"SBMNETJOB","SBMNETJOB"},
	       {"SBMRJEJOB","SBMRJEJOB"},
	       {"SBMRMTCMD","SBMRMTCMD"},
	       {"SELECT","SELECT"},
	       {"SETASPGRP","SETASPGRP"},
	       {"SETATNPGM","SETATNPGM"},
	       {"SETCSTDTA","SETCSTDTA"},
	       {"SETDEPJS","SETDEPJS"},
	       {"SETDLJS","SETDLJS"},
	       {"SETKBDMAP","SETKBDMAP"},
	       {"SETMEDBRM","SETMEDBRM"},
	       {"SETOBJACC","SETOBJACC"},
	       {"SETPGMINF","SETPGMINF"},
	       {"SETRTVBRM","SETRTVBRM"},
	       {"SETSTPJS","SETSTPJS"},
	       {"SETTAPCGY","SETTAPCGY"},
	       // Not Authorized {"SETUSRBRM","SETUSRBRM"},
	       {"SETVTMAP","SETVTMAP"},
	       {"SETVTTBL","SETVTTBL"},
	       {"SIGNOFF","SIGNOFF"},
	       {"SLTCMD","SLTCMD"},
	       {"SNDBRKMSG","SNDBRKMSG"},
	       {"SNDDST","SNDDST"},
	       {"SNDDSTJS","SNDDSTJS"},
	       {"SNDF","SNDF"},
	       {"SNDFAX","SNDFAX"},
	       {"SNDJRNE","SNDJRNE"},
	       {"SNDMSG","SNDMSG"},
	       {"SNDNETF","SNDNETF"},
	       {"SNDNETMSG","SNDNETMSG"},
	       {"SNDNETSPLF","SNDNETSPLF"},
	       {"SNDPGMMSG","SNDPGMMSG"},
	       {"SNDRCVF","SNDRCVF"},
	       {"SNDRJECMD","SNDRJECMD"},
	       {"SNDRPTJS","SNDRPTJS"},
	       {"SNDRPY","SNDRPY"},
	       {"SNDTCPSPLF","SNDTCPSPLF"},
	       {"SNDTIEF","SNDTIEF"},
	       {"SNDUSRMSG","SNDUSRMSG"},
	       // Not Authorized {"SPDMQMCLQM","SPDMQMCLQM"},
	       {"STATFS","STATFS"},
	       {"STRAGTSRV","STRAGTSRV"},
	       {"STRAPF","STRAPF"},
	       {"STRARCBRM","STRARCBRM"},
	       {"STRBALBRM","STRBALBRM"},
	       {"STRBKUBRM","STRBKUBRM"},
	       {"STRBLDIMPT","STRBLDIMPT"},
	       {"STRBLDSVR","STRBLDSVR"},
	       {"STRCBLDBG","STRCBLDBG"},
	       {"STRCGU","STRCGU"},
	       {"STRCLNUP","STRCLNUP"},
	       {"STRCMTCTL","STRCMTCTL"},
	       {"STRCODE","STRCODE"},
	       {"STRCODECMD","STRCODECMD"},
	       {"STRCPYSCN","STRCPYSCN"},
	       {"STRDBG","STRDBG"},
	       {"STRDBMON","STRDBMON"},
	       {"STRDBRDR","STRDBRDR"},
	       {"STRDFU","STRDFU"},
	       {"STRDIGQRY","STRDIGQRY"},
	       {"STRDIRSHD","STRDIRSHD"},
	       {"STRDKTRDR","STRDKTRDR"},
	       {"STRDKTWTR","STRDKTWTR"},
	       {"STRDNSQRY","STRDNSQRY"},
	       {"STRDPRAPY","STRDPRAPY"},
	       {"STRDPRCAP","STRDPRCAP"},
	       {"STREDU","STREDU"},
	       {"STREML3270","STREML3270"},
	       {"STREPMENV","STREPMENV"},
	       {"STREXPBRM","STREXPBRM"},
	       {"STRFAXSPT","STRFAXSPT"},
	       {"STRFMA","STRFMA"},
	       // Not Authorized {"STRFNTDWN","STRFNTDWN"},
	       {"STRGRPJS","STRGRPJS"},
	       {"STRHOSTQRY","STRHOSTQRY"},
	       {"STRHTTPCRL","STRHTTPCRL"},
	       {"STRIDD","STRIDD"},
	       {"STRISDB","STRISDB"},
	       {"STRITF","STRITF"},
	       // Not Authorized {"STRJOBTRC","STRJOBTRC"},
	       {"STRJRN","STRJRN"},
	       {"STRJRNAP","STRJRNAP"},
	       {"STRJRNLIB","STRJRNLIB"},
	       {"STRJRNOBJ","STRJRNOBJ"},
	       {"STRJRNPF","STRJRNPF"},
	       {"STRJS","STRJS"},
	       {"STRLOGSVR","STRLOGSVR"},
	       {"STRMGRBRM","STRMGRBRM"},
	       {"STRMNTBRM","STRMNTBRM"},
	       {"STRMOD","STRMOD"},
	       // Not Authorized {"STRMQM","STRMQM"},
	       // Not Authorized {"STRMQMBRK","STRMQMBRK"},
	       // Not Authorized {"STRMQMCHL","STRMQMCHL"},
	       // Not Authorized {"STRMQMCHLI","STRMQMCHLI"},
	       // Not Authorized {"STRMQMCSVR","STRMQMCSVR"},
	       // Not Authorized {"STRMQMDLQ","STRMQMDLQ"},
	       // Not Authorized {"STRMQMLSR","STRMQMLSR"},
	       // Not Authorized {"STRMQMMQSC","STRMQMMQSC"},
	       // Not Authorized {"STRMQMSVC","STRMQMSVC"},
	       // Not Authorized {"STRMQMTRM","STRMQMTRM"},
	       {"STRNETINS","STRNETINS"},
	       {"STRPASTHR","STRPASTHR"},
	       {"STRPCCMD","STRPCCMD"},
	       {"STRPCO","STRPCO"},
	       {"STRPDM","STRPDM"},
	       // Not Authorized {"STRPFRG","STRPFRG"},
	       // Not Authorized {"STRPFRT","STRPFRT"},
	       {"STRPGMEXP","STRPGMEXP"},
	       {"STRPGMMNU","STRPGMMNU"},
	       {"STRPJ","STRPJ"},
	       {"STRPRTEML","STRPRTEML"},
	       {"STRPRTWTR","STRPRTWTR"},
	       {"STRPTL","STRPTL"},
	       {"STRQM","STRQM"},
	       {"STRQMPRC","STRQMPRC"},
	       {"STRQMQRY","STRQMQRY"},
	       {"STRQRY","STRQRY"},
	       {"STRQSH","STRQSH"},
	       {"STRQST","STRQST"},
	       // Not Authorized {"STRRCYBRM","STRRCYBRM"},
	       {"STRREXPRC","STRREXPRC"},
	       {"STRRJECSL","STRRJECSL"},
	       {"STRRJERDR","STRRJERDR"},
	       {"STRRJESSN","STRRJESSN"},
	       {"STRRJEWTR","STRRJEWTR"},
	       {"STRRLU","STRRLU"},
	       {"STRRMTWTR","STRRMTWTR"},
	       {"STRRSESVR","STRRSESVR"},
	       {"STRSAVSYNC","STRSAVSYNC"},
	       {"STRSBS","STRSBS"},
	       {"STRSBSBRM","STRSBSBRM"},
	       {"STRSCHIDX","STRSCHIDX"},
	       {"STRSDA","STRSDA"},
	       {"STRSEU","STRSEU"},
	       {"STRSPTN","STRSPTN"},
	       {"STRSQL","STRSQL"},
	       {"STRS36","STRS36"},
	       {"STRS36PRC","STRS36PRC"},
	       {"STRTCPFTP","STRTCPFTP"},
	       {"STRTCPTELN","STRTCPTELN"},
	       {"STRTFMMGR","STRTFMMGR"},
	       {"STRTIESSN","STRTIESSN"},
	       {"STRVFYMON","STRVFYMON"},
	       // Not Authorized {"STRWEBQRY","STRWEBQRY"},
	       {"SUBR","SUBR"},
	       {"TELNET","TELNET"},
	       {"TFRBCHJOB","TFRBCHJOB"},
	       {"TFRCTL","TFRCTL"},
	       {"TFRGRPJOB","TFRGRPJOB"},
	       {"TFRJOB","TFRJOB"},
	       {"TFRPASTHR","TFRPASTHR"},
	       {"TFRSECJOB","TFRSECJOB"},
	       {"TRACEROUTE","TRACEROUTE"},
	       // Not Authorized {"TRCMQM","TRCMQM"},
	       {"TRCREX","TRCREX"},
	       {"TRCTCPRTE","TRCTCPRTE"},
	       // Not Authorized {"TRCWEBQRY","TRCWEBQRY"},
	       {"TRNCKMKSF","TRNCKMKSF"},
	       {"UPDBUILDER","UPDBUILDER"},
	       {"UPDDTA","UPDDTA"},
	       {"UPDPGM","UPDPGM"},
	       {"UPDSRVPGM","UPDSRVPGM"},
	       {"VFYAPPCCNN","VFYAPPCCNN"},
	       {"VFYBPR","VFYBPR"},
	       {"VFYIMGCLG","VFYIMGCLG"},
	       {"VFYMOVBRM","VFYMOVBRM"},
	       {"VFYOBJ","VFYOBJ"},
	       // Not Authorized {"VFYOPCCNN","VFYOPCCNN"},
	       {"VFYSRVCFG","VFYSRVCFG"},
	       {"VFYTCPCNN","VFYTCPCNN"},
	       {"VRYCFG","VRYCFG"},
	       {"WAIT","WAIT"},
	       {"WHEN","WHEN"},
	       {"WM","WRKMBRPDM"},
	       {"WO","WRKOBJ"},
	       {"WRKACTJOB","WRKACTJOB"},
	       {"WRKALR","WRKALR"},
	       {"WRKALRD","WRKALRD"},
	       {"WRKALRTBL","WRKALRTBL"},
	       {"WRKAPPNSTS","WRKAPPNSTS"},
	       {"WRKARMJOB","WRKARMJOB"},
	       {"WRKASPBRM","WRKASPBRM"},
	       {"WRKASPJOB","WRKASPJOB"},
	       {"WRKAUT","WRKAUT"},
	       {"WRKAUTL","WRKAUTL"},
	       {"WRKBLDID","WRKBLDID"},
	       {"WRKBLDJOB","WRKBLDJOB"},
	       {"WRKBLDOPT","WRKBLDOPT"},
	       {"WRKBLDSVR","WRKBLDSVR"},
	       {"WRKBNDDIR","WRKBNDDIR"},
	       {"WRKBNDDIRE","WRKBNDDIRE"},
	       {"WRKBPRINF","WRKBPRINF"},
	       {"WRKBPTBL","WRKBPTBL"},
	       {"WRKCALBRM","WRKCALBRM"},
	       {"WRKCFGL","WRKCFGL"},
	       {"WRKCFGSTS","WRKCFGSTS"},
	       {"WRKCHTFMT","WRKCHTFMT"},
	       {"WRKCLS","WRKCLS"},
	       {"WRKCLSBRM","WRKCLSBRM"},
	       {"WRKCMD","WRKCMD"},
	       {"WRKCMTDFN","WRKCMTDFN"},
	       {"WRKCNNL","WRKCNNL"},
	       {"WRKCNRBRM","WRKCNRBRM"},
	       {"WRKCOSD","WRKCOSD"},
	       {"WRKCSI","WRKCSI"},
	       {"WRKCTLD","WRKCTLD"},
	       {"WRKCTLGBRM","WRKCTLGBRM"},
	       {"WRKDBFIDD","WRKDBFIDD"},
	       {"WRKDDMF","WRKDDMF"},
	       {"WRKDEVBRM","WRKDEVBRM"},
	       {"WRKDEVD","WRKDEVD"},
	       {"WRKDIRE","WRKDIRE"},
	       {"WRKDIRLOC","WRKDIRLOC"},
	       {"WRKDIRSHD","WRKDIRSHD"},
	       {"WRKDOC","WRKDOC"},
	       {"WRKDOCLIB","WRKDOCLIB"},
	       {"WRKDOCPRTQ","WRKDOCPRTQ"},
	       {"WRKDSKSTS","WRKDSKSTS"},
	       {"WRKDSTL","WRKDSTL"},
	       {"WRKDTAARA","WRKDTAARA"},
	       {"WRKDTADCT","WRKDTADCT"},
	       {"WRKDTADFN","WRKDTADFN"},
	       {"WRKDTAQ","WRKDTAQ"},
	       {"WRKEDTD","WRKEDTD"},
	       {"WRKENVVAR","WRKENVVAR"},
	       {"WRKF","WRKF"},
	       {"WRKFAX","WRKFAX"},
	       {"WRKFAXDST","WRKFAXDST"},
	       {"WRKFAXFA","WRKFAXFA"},
	       {"WRKFAXMST","WRKFAXMST"},
	       {"WRKFAXPRF","WRKFAXPRF"},
	       {"WRKFAXQ","WRKFAXQ"},
	       // Not Authorized {"WRKFCNARA","WRKFCNARA"},
	       {"WRKFCNUSG","WRKFCNUSG"},
	       {"WRKFCT","WRKFCT"},
	       {"WRKFLR","WRKFLR"},
	       {"WRKFLRBRM","WRKFLRBRM"},
	       {"WRKFNTRSC","WRKFNTRSC"},
	       {"WRKFORMDF","WRKFORMDF"},
	       {"WRKFTR","WRKFTR"},
	       {"WRKFTRACNE","WRKFTRACNE"},
	       {"WRKFTRSLTE","WRKFTRSLTE"},
	       {"WRKGSS","WRKGSS"},
	       {"WRKHDWPRD","WRKHDWPRD"},
	       {"WRKHDWRSC","WRKHDWRSC"},
	       {"WRKHLDOPTF","WRKHLDOPTF"},
	       {"WRKHSTJS","WRKHSTJS"},
	       {"WRKIMGCLG","WRKIMGCLG"},
	       {"WRKIMGCLGE","WRKIMGCLGE"},
	       {"WRKIPXD","WRKIPXD"},
	       {"WRKJOB","WRKJOB"},
	       {"WRKJOBD","WRKJOBD"},
	       {"WRKJOBJS","WRKJOBJS"},
	       {"WRKJOBLOG","WRKJOBLOG"},
	       {"WRKJOBQ","WRKJOBQ"},
	       {"WRKJOBQD","WRKJOBQD"},
	       {"WRKJOBSCDE","WRKJOBSCDE"},
	       {"WRKJRNA","WRKJRNA"},
	       {"WRKJRNRCV","WRKJRNRCV"},
	       {"WRKJVMJOB","WRKJVMJOB"},
	       {"WRKLANADPT","WRKLANADPT"},
	       {"WRKLBRM","WRKLBRM"},
	       {"WRKLIB","WRKLIB"},
	       {"WRKLIBPDM","WRKLIBPDM"},
	       {"WRKLIND","WRKLIND"},
	       {"WRKLNK","WRKLNK"},
	       {"WRKLNKBRM","WRKLNKBRM"},
	       {"WRKLOCBRM","WRKLOCBRM"},
	       {"WRKMBRPDM","WRKMBRPDM"},
	       {"WRKMEDBRM","WRKMEDBRM"},
	       {"WRKMEDIBRM","WRKMEDIBRM"},
	       {"WRKMGRIBRM","WRKMGRIBRM"},
	       {"WRKMLBBRM","WRKMLBBRM"},
	       {"WRKMLBRSCQ","WRKMLBRSCQ"},
	       {"WRKMLBSTS","WRKMLBSTS"},
	       {"WRKMLMBRM","WRKMLMBRM"},
	       {"WRKMNU","WRKMNU"},
	       {"WRKMOD","WRKMOD"},
	       {"WRKMODD","WRKMODD"},
	       // Not Authorized {"WRKMQM","WRKMQM"},
	       // Not Authorized {"WRKMQMAUT","WRKMQMAUT"},
	       // Not Authorized {"WRKMQMAUTD","WRKMQMAUTD"},
	       // Not Authorized {"WRKMQMAUTI","WRKMQMAUTI"},
	       // Not Authorized {"WRKMQMCHL","WRKMQMCHL"},
	       // Not Authorized {"WRKMQMCHST","WRKMQMCHST"},
	       // Not Authorized {"WRKMQMCL","WRKMQMCL"},
	       // Not Authorized {"WRKMQMCLQ","WRKMQMCLQ"},
	       // Not Authorized {"WRKMQMCONN","WRKMQMCONN"},
	       // Not Authorized {"WRKMQMLSR","WRKMQMLSR"},
	       // Not Authorized {"WRKMQMMSG","WRKMQMMSG"},
	       // Not Authorized {"WRKMQMNL","WRKMQMNL"},
	       // Not Authorized {"WRKMQMPRC","WRKMQMPRC"},
	       // Not Authorized {"WRKMQMQ","WRKMQMQ"},
	       // Not Authorized {"WRKMQMQSTS","WRKMQMQSTS"},
	       // Not Authorized {"WRKMQMSVC","WRKMQMSVC"},
	       // Not Authorized {"WRKMQMTRN","WRKMQMTRN"},
	       {"WRKMSG","WRKMSG"},
	       {"WRKMSGD","WRKMSGD"},
	       {"WRKMSGF","WRKMSGF"},
	       {"WRKMSGQ","WRKMSGQ"},
	       {"WRKNAMSMTP","WRKNAMSMTP"},
	       {"WRKNCK","WRKNCK"},
	       {"WRKNETF","WRKNETF"},
	       {"WRKNETJOBE","WRKNETJOBE"},
	       {"WRKNETTBLE","WRKNETTBLE"},
	       {"WRKNODL","WRKNODL"},
	       {"WRKNODLE","WRKNODLE"},
	       {"WRKNTBD","WRKNTBD"},
	       {"WRKNWID","WRKNWID"},
	       {"WRKNWSD","WRKNWSD"},
	       {"WRKNWSENR","WRKNWSENR"},
	       {"WRKNWSSTG","WRKNWSSTG"},
	       {"WRKNWSSTS","WRKNWSSTS"},
	       {"WRKOBJ","WRKOBJ"},
	       {"WRKOBJBRM","WRKOBJBRM"},
	       {"WRKOBJLCK","WRKOBJLCK"},
	       {"WRKOBJOWN","WRKOBJOWN"},
	       {"WRKOBJPDM","WRKOBJPDM"},
	       {"WRKOBJPGP","WRKOBJPGP"},
	       {"WRKOBJPVT","WRKOBJPVT"},
	       {"WRKOPCACT","WRKOPCACT"},
	       {"WRKOPTDIR","WRKOPTDIR"},
	       {"WRKOPTF","WRKOPTF"},
	       {"WRKOPTVOL","WRKOPTVOL"},
	       {"WRKOUTQ","WRKOUTQ"},
	       {"WRKOUTQD","WRKOUTQD"},
	       {"WRKOVL","WRKOVL"},
	       {"WRKPAGDFN","WRKPAGDFN"},
	       {"WRKPAGSEG","WRKPAGSEG"},
	       {"WRKPCLTBLE","WRKPCLTBLE"},
	       {"WRKPCYBRM","WRKPCYBRM"},
	       {"WRKPDFMAPE","WRKPDFMAPE"},
	       {"WRKPFCST","WRKPFCST"},
	       {"WRKPFDL","WRKPFDL"},
	       {"WRKPGM","WRKPGM"},
	       {"WRKPMRMTS","WRKPMRMTS"},
	       {"WRKPMRPTO","WRKPMRPTO"},
	       {"WRKPMSCH","WRKPMSCH"},
	       {"WRKPNLGRP","WRKPNLGRP"},
	       {"WRKPRDBPR","WRKPRDBPR"},
	       {"WRKPRDINF","WRKPRDINF"},
	       {"WRKPRTSTS","WRKPRTSTS"},
	       {"WRKPSFCFG","WRKPSFCFG"},
	       {"WRKQMFORM","WRKQMFORM"},
	       {"WRKQMQRY","WRKQMQRY"},
	       {"WRKQRY","WRKQRY"},
	       {"WRKQST","WRKQST"},
	       {"WRKRCVFAX","WRKRCVFAX"},
	       {"WRKRCYBRM","WRKRCYBRM"},
	       {"WRKRDBDIRE","WRKRDBDIRE"},
	       {"WRKRDR","WRKRDR"},
	       {"WRKREGINF","WRKREGINF"},
	       {"WRKRJESSN","WRKRJESSN"},
	       {"WRKRPYLE","WRKRPYLE"},
	       {"WRKRTDCFG","WRKRTDCFG"},
	       {"WRKSAVFBRM","WRKSAVFBRM"},
	       {"WRKSBMJOB","WRKSBMJOB"},
	       {"WRKSBS","WRKSBS"},
	       {"WRKSBSD","WRKSBSD"},
	       {"WRKSBSJOB","WRKSBSJOB"},
	       {"WRKSCHIDX","WRKSCHIDX"},
	       {"WRKSCHIDXE","WRKSCHIDXE"},
	       {"WRKSFWAGR","WRKSFWAGR"},
	       {"WRKSHRPOOL","WRKSHRPOOL"},
	       {"WRKSOC","WRKSOC"},
	       {"WRKSPADCT","WRKSPADCT"},
	       {"WRKSPLF","WRKSPLF"},
	       {"WRKSPLFA","WRKSPLFA"},
	       {"WRKSPLFBRM","WRKSPLFBRM"},
	       {"WRKSRVPGM","WRKSRVPGM"},
	       {"WRKSRVTBLE","WRKSRVTBLE"},
	       {"WRKSSND","WRKSSND"},
	       {"WRKSYSSTS","WRKSYSSTS"},
	       {"WRKSYSVAL","WRKSYSVAL"},
	       {"WRKS36","WRKS36"},
	       {"WRKS36PGMA","WRKS36PGMA"},
	       {"WRKS36PRCA","WRKS36PRCA"},
	       {"WRKS36SRCA","WRKS36SRCA"},
	       {"WRKTAPCTG","WRKTAPCTG"},
	       {"WRKTBL","WRKTBL"},
	       {"WRKTCPPTP","WRKTCPPTP"},
	       {"WRKTCPSTS","WRKTCPSTS"},
	       {"WRKTEF","WRKTEF"},
	       {"WRKTIE","WRKTIE"},
	       {"WRKTIMZON","WRKTIMZON"},
	       {"WRKTSIRTG","WRKTSIRTG"},
	       {"WRKUSRJOB","WRKUSRJOB"},
	       {"WRKUSRPRF","WRKUSRPRF"},
	       {"WRKVFYLIST","WRKVFYLIST"},
	       {"WRKWTR","WRKWTR"},

	   } ;

	   boolean passed = true;
	   String [] reconnectCommands = {
	       "CHGUSRAUD",
	       "RNMDKT",
	   }; 
 	   // create a CommandHelpRetriever
	   // There is a bug in the command help retriever that after so many iterations, 
	   // the replacement text is not longer correct. We create a new AS400 object at various 
	   // intervals to avoid this problem . 
	   AS400 as400 = new AS400(systemObject_); 
	   for (int commandIndex = 0; commandIndex < commandsAndExpectedStrings.length; commandIndex++) {
	     
	       for (int i = 0; i < reconnectCommands.length; i++) {
	         if (reconnectCommands[i].equals(commandsAndExpectedStrings[commandIndex][0])) {
	           as400.close(); 
	                 as400 = new AS400(systemObject_); 
	         }
	       }
	       String[] commandAndExpected = commandsAndExpectedStrings[commandIndex]; 

	       CommandHelpRetriever commandHelp = new CommandHelpRetriever();
	       CommandList cmdList = new CommandList(as400, "QSYS", commandAndExpected[0]);
	       Command[] cmds = cmdList.generateList();
	       System.out.println("-->["+commandIndex+"]Command="+commandAndExpected[0]); 
	       sb.append("\n-->Command="+commandAndExpected[0]+"\n");
               try {
                 if (cmds.length == 0) {
                   System.out.println("Warning:  Command " + commandAndExpected[0] + " did not generate list");
                   sb.append("Warning:  Command " + commandAndExpected[0] + " did not generate list\n");
                 } else {
                   String help = commandHelp.generateHTML(cmds[0]);

                   if (help == null) {
                     sb.append("FAILED:  Command help is empty\n");
                     passed = false;
                   } else {
                     for (int i = 1; i < commandAndExpected.length; i++) {
                       if (help.indexOf(commandAndExpected[i]) < 0) {
                         sb.append("Returned help : \n");
                         sb.append("FAILED: Did not find expected string " + commandAndExpected[i] + "\n");
                         passed = false;
                         failList.append(commandAndExpected[0] + "\n");
                       }
                     }
                   }
                 }
	       } catch (Exception e) {
		   // Ignore any not authorized or not available 
		   String eMessage = e.toString();
		   if (eMessage.indexOf("CPF9802") >= 0 || eMessage.indexOf("CPF6E3B") >= 0  ) {
		       System.out.println("Warning:  Ignoring exception: "+eMessage);
		       sb.append("Warning: On "+commandAndExpected[0]+" Ignoring exception: "+eMessage+"\n");
		   } else { 
		       passed = false;
		       failList.append(commandAndExpected[0]+"\n"); 
		       sb.append("FAILED: On "+commandAndExpected[0]+" Exception taken "+e.toString()+"\n");
		       printStackTraceToStringBuffer(e, sb);
		   }
	       } 
	   }
	   as400.close(); 
	   assertCondition(passed, sb.toString());
	   if (!passed) { 
		   System.out.println("Fail list is "+failList.toString()); 
		   
	   }
       }
       catch (Exception e) {
         failed(e, "Unexpected exception." + sb.toString());

         System.out.flush();
         System.err.flush();
         System.out.println("====================================");
         System.out.flush();
         System.err.flush();
         Throwable cause = e.getCause();
         while (cause != null) {
           System.out.flush();
           System.err.flush();
           System.out.println("Caused by ");
           System.out.flush();
           System.err.flush();
           cause.printStackTrace();
           cause = cause.getCause();
         }

       }


   }


   /**
    * run generateHTML on a various commands in QSYS.
    */ 
   public void Var010() { 

       StringBuffer sb = new StringBuffer("New testcases added   Fixed JTOpen 7.4\n");

       try
       {

         // 
         // this list create on V5R4 using
         //   system "dspobjd qsys/*all *cmd" | grep CMD | sed 's/^ *\([^ ][^ ]*\) *.CMD.*/{"\1","\1"},/'
         //   
           String [][] commandsAndExpectedStrings = {
                   {"CHGTIMZON","CHGTIMZON"},
        		   {"CHGUSRAUD","CHGUSRAUD"},
        		   {"CHGUSRPRF","CHGUSRPRF"},
        		   {"CHGUSRTRC","CHGUSRTRC"},
        		   {"CHGVAR","CHGVAR"},
        		   {"CHGWTR","CHGWTR"},
        		   /* 
        		   {"CHKBLDJOB","CHKBLDJOB"},
        		   {"CHKOBJ","CHKOBJ"},
        		   {"CHKOPTVOL","CHKOPTVOL"},
        		   {"CLOSE","CLOSE"},
        		   {"CLRJOBQ","CLRJOBQ"},
        		   {"CLROUTQ","CLROUTQ"},
        		   {"CMPJRNIMG","CMPJRNIMG"},
        		   {"COMMIT","COMMIT"},
        		   {"CPROBJ","CPROBJ"},
        		   {"CPYF","CPYF"},
        		   {"CPYFRMDKT","CPYFRMDKT"},
        		   {"CPYFRMQRYF","CPYFRMQRYF"},
        		   {"CPYFRMTAP","CPYFRMTAP"},
        		   {"CPYOPT","CPYOPT"},
        		   {"CPYSPLF","CPYSPLF"},
        		   {"CPYSRCF","CPYSRCF"},
        		   {"CPYTODKT","CPYTODKT"},
        		   {"CPYTOTAP","CPYTOTAP"},
        		   {"CRTALRTBL","CRTALRTBL"},
        		   {"CRTAUTL","CRTAUTL"},
        		   {"CRTCKMKSF","CRTCKMKSF"},
        		   {"CRTDTAARA","CRTDTAARA"},
        		   {"CRTDTAQ","CRTDTAQ"},
        		   {"CRTDUPOBJ","CRTDUPOBJ"},
        		   {"CRTFNTRSC","CRTFNTRSC"},
        		   {"CRTFORMDF","CRTFORMDF"},
        		   {"CRTFTR","CRTFTR"},
        		   {"CRTIMGCLG","CRTIMGCLG"},
        		   {"CRTJOBQ","CRTJOBQ"},
        		   {"CRTJRN","CRTJRN"},
        		   {"CRTJRNRCV","CRTJRNRCV"},
        		   {"CRTMSGF","CRTMSGF"},
        		   {"CRTMSGQ","CRTMSGQ"},
        		   {"CRTNODL","CRTNODL"},
        		   {"CRTOUTQ","CRTOUTQ"},
        		   {"CRTOVL","CRTOVL"},
        		   {"CRTPAGDFN","CRTPAGDFN"},
        		   {"CRTPAGSEG","CRTPAGSEG"},
        		   {"CRTSPADCT","CRTSPADCT"},
        		   {"CRTSRVCFG","CRTSRVCFG"},
        		   {"CRTS36MSGF","CRTS36MSGF"},
        		   {"CRTTBL","CRTTBL"},
        		   {"CRTUSRPRF","CRTUSRPRF"},
        		   {"CVTDAT","CVTDAT"},
        		   {"CVTOPTBKU","CVTOPTBKU"},
        		   {"DCL","DCL"},
        		   {"DCPOBJ","DCPOBJ"},
        		   {"DIG","DIG"},
        		   {"DLTALRTBL","DLTALRTBL"},
        		   {"DLTAUTL","DLTAUTL"},
        		   {"DLTBNDDIR","DLTBNDDIR"},
        		   {"DLTCFGL","DLTCFGL"},
        		   {"DLTCLS","DLTCLS"},
        		   {"DLTCMD","DLTCMD"},
        		   {"DLTCOSD","DLTCOSD"},
        		   {"DLTCTLD","DLTCTLD"},
        		   {"DLTDEVD","DLTDEVD"},
        		   {"DLTDST","DLTDST"},
        		   {"DLTDTAARA","DLTDTAARA"},
        		   {"DLTDTAQ","DLTDTAQ"},
        		   {"DLTEDTD","DLTEDTD"},
        		   {"DLTF","DLTF"},
        		   {"DLTIGCDCT","DLTIGCDCT"},
        		   {"DLTIMGCLG","DLTIMGCLG"},
        		   {"DLTJOBD","DLTJOBD"},
        		   {"DLTJOBQ","DLTJOBQ"},
        		   {"DLTJRN","DLTJRN"},
        		   {"DLTJRNRCV","DLTJRNRCV"},
        		   {"DLTLIND","DLTLIND"},
        		   {"DLTMEDDFN","DLTMEDDFN"},
        		   {"DLTMNU","DLTMNU"},
        		   {"DLTMOD","DLTMOD"},
        		   {"DLTMODD","DLTMODD"},
        		   {"DLTMSGF","DLTMSGF"},
        		   {"DLTMSGQ","DLTMSGQ"},
        		   {"DLTNETF","DLTNETF"},
        		   {"DLTNODGRP","DLTNODGRP"},
        		   {"DLTNODL","DLTNODL"},
        		   {"DLTOUTQ","DLTOUTQ"},
        		   {"DLTPAGDFN","DLTPAGDFN"},
        		   {"DLTPDG","DLTPDG"},
        		   {"DLTPGM","DLTPGM"},
        		   {"DLTPNLGRP","DLTPNLGRP"},
        		   {"DLTQMFORM","DLTQMFORM"},
        		   {"DLTQMQRY","DLTQMQRY"},
        		   {"DLTSBSD","DLTSBSD"},
        		   {"DLTSCHIDX","DLTSCHIDX"},
        		   {"DLTSPADCT","DLTSPADCT"},
        		   {"DLTSPLF","DLTSPLF"},
        		   {"DLTSRVCFG","DLTSRVCFG"},
        		   {"DLTSRVPGM","DLTSRVPGM"},
        		   {"DLTTBL","DLTTBL"},
        		   {"DLTTIMZON","DLTTIMZON"},
        		   {"DLTUSRIDX","DLTUSRIDX"},
        		   {"DLTUSRPRF","DLTUSRPRF"},
        		   {"DLTUSRQ","DLTUSRQ"},
        		   {"DLTUSRSPC","DLTUSRSPC"},
        		   {"DLTUSRTRC","DLTUSRTRC"},
        		   {"DMPUSRTRC","DMPUSRTRC"},
        		   {"DOFOR","DOFOR"},
        		   {"DOUNTIL","DOUNTIL"},
        		   {"DSCJOB","DSCJOB"},
        		   {"DSPACTPJ","DSPACTPJ"},
        		   {"DSPAUTL","DSPAUTL"},
        		   {"DSPCKMKSFE","DSPCKMKSFE"},
        		   {"DSPCMD","DSPCMD"},
        		   {"DSPDBR","DSPDBR"},
        		   {"DSPDKT","DSPDKT"},
        		   {"DSPF","DSPF"},
        		   {"DSPFD","DSPFD"},
        		   {"DSPFNTRSCA","DSPFNTRSCA"},
        		   {"DSPHDWRSC","DSPHDWRSC"},
        		   {"DSPIGCDCT","DSPIGCDCT"},
        		   {"DSPJOB","DSPJOB"},
        		   {"DSPJOBLOG","DSPJOBLOG"},
        		   {"DSPJRN","DSPJRN"},
        		   {"DSPLIBD","DSPLIBD"},
        		   {"DSPMOD","DSPMOD"},
        		   {"DSPMSG","DSPMSG"},
        		   {"DSPNODGRP","DSPNODGRP"},
        		   {"DSPOBJAUT","DSPOBJAUT"},
        		   {"DSPOBJD","DSPOBJD"},
        		   {"DSPOPT","DSPOPT"},
        		   {"DSPPGM","DSPPGM"},
        		   {"DSPPGMREF","DSPPGMREF"},
        		   {"DSPRCDLCK","DSPRCDLCK"},
        		   {"DSPSPLF","DSPSPLF"},
        		   {"DSPSRVPGM","DSPSRVPGM"},
        		   {"DUPOPT","DUPOPT"},
        		   {"EDTAUTL","EDTAUTL"},
        		   {"EDTF","EDTF"},
        		   {"EDTIGCDCT","EDTIGCDCT"},
        		   {"EDTLIBL","EDTLIBL"},
        		   {"EDTOBJAUT","EDTOBJAUT"},
        		   {"EDTS36PRCA","EDTS36PRCA"},
        		   {"EDTS36SRCA","EDTS36SRCA"},
        		   {"ELSE","ELSE"},
        		   {"ENDCPYSCN","ENDCPYSCN"},
        		   {"ENDDBMON","ENDDBMON"},
        		   {"ENDGRPJOB","ENDGRPJOB"},
        		   {"ENDJOB","ENDJOB"},
        		   {"ENDJRNPF","ENDJRNPF"},
        		   {"ENDLOGSVR","ENDLOGSVR"},
        		   {"ENDPJ","ENDPJ"},
        		   {"ENDRDR","ENDRDR"},
        		   {"ENDWTR","ENDWTR"},
        		   {"GENCKMKSFE","GENCKMKSFE"},
        		   {"GENJVMDMP","GENJVMDMP"},
        		   {"GETTEFE","GETTEFE"},
        		   {"GRTOBJAUT","GRTOBJAUT"},
        		   {"GRTUSRAUT","GRTUSRAUT"},
        		   {"HLDJOB","HLDJOB"},
        		   {"HLDJOBQ","HLDJOBQ"},
        		   {"HLDOUTQ","HLDOUTQ"},
        		   {"HLDRDR","HLDRDR"},
        		   {"HLDSPLF","HLDSPLF"},
        		   {"HLDWTR","HLDWTR"},
        		   {"IF","IF"},
        		   {"INZOPT","INZOPT"},
        		   {"INZPCS","INZPCS"},
        		   {"INZPFM","INZPFM"},
        		   {"ITERATE","ITERATE"},
        		   {"LPR","LPR"},
        		   {"MONMSG","MONMSG"},
        		   {"MOVOBJ","MOVOBJ"},
        		   {"MRGTCPHT","MRGTCPHT"},
        		   {"OPNDBF","OPNDBF"},
        		   {"OPNQRYF","OPNQRYF"},
        		   {"PGM","PGM"},
        		   {"PING","PING"},
        		   {"PRTJVMJOB","PRTJVMJOB"},
        		   {"RCLLNK","RCLLNK"},
        		   {"RCVF","RCVF"},
        		   {"RCVJRNE","RCVJRNE"},
        		   {"RCVMSG","RCVMSG"},
        		   {"RCVNETF","RCVNETF"},
        		   {"RGZPFM","RGZPFM"},
        		   {"RLSJOB","RLSJOB"},
        		   {"RLSJOBQ","RLSJOBQ"},
        		   {"RLSOUTQ","RLSOUTQ"},
        		   {"RLSRDR","RLSRDR"},
        		   {"RLSSPLF","RLSSPLF"},
        		   {"RLSWTR","RLSWTR"},
        		   {"RMVAUTLE","RMVAUTLE"},
        		   {"RMVBNDDIRE","RMVBNDDIRE"},
        		   {"RMVCKMKSFE","RMVCKMKSFE"},
        		   {"RMVDSTLE","RMVDSTLE"},
        		   {"RMVFTRACNE","RMVFTRACNE"},
        		   {"RMVFTRSLTE","RMVFTRSLTE"},
        		   {"RMVM","RMVM"},
        		   {"RMVMSG","RMVMSG"},
        		   {"RMVMSGD","RMVMSGD"},
        		   {"RMVRIPFLT","RMVRIPFLT"},
        		   {"RMVSMTPLE","RMVSMTPLE"},
        		   {"RMVTCPIFC","RMVTCPIFC"},
        		   {"RMVTCPPORT","RMVTCPPORT"},
        		   {"RMVTCPRTE","RMVTCPRTE"},
        		   {"RNMDLO","RNMDLO"},
        		   {"RNMOBJ","RNMOBJ"},
        		   {"RTVBNDSRC","RTVBNDSRC"},
        		   {"RTVCFGSRC","RTVCFGSRC"},
        		   {"RTVCLSRC","RTVCLSRC"},
        		   {"RTVGRPA","RTVGRPA"},
        		   {"RTVJOBA","RTVJOBA"},
        		   {"RTVJRNE","RTVJRNE"},
        		   {"RTVLIBD","RTVLIBD"},
        		   {"RTVMBRD","RTVMBRD"},
        		   {"RTVMSG","RTVMSG"},
        		   {"RTVOBJD","RTVOBJD"},
        		   {"RTVPDGPRF","RTVPDGPRF"},
        		   {"RTVPWRSCDE","RTVPWRSCDE"},
        		   {"RTVS36A","RTVS36A"},
        		   {"RVKOBJAUT","RVKOBJAUT"},
        		   {"SAVCFG","SAVCFG"},
        		   {"SAVCHGOBJ","SAVCHGOBJ"},
        		   {"SAVDLO","SAVDLO"},
        		   {"SAVLIB","SAVLIB"},
        		   {"SAVOBJ","SAVOBJ"},
        		   {"SAVSAVFDTA","SAVSAVFDTA"},
        		   {"SAVSECDTA","SAVSECDTA"},
        		   {"SAVSYS","SAVSYS"},
        		   {"SAVSYSINF","SAVSYSINF"},
        		   {"SAVS36F","SAVS36F"},
        		   {"SAVS36LIBM","SAVS36LIBM"},
        		   {"SBMDBJOB","SBMDBJOB"},
        		   {"SBMDKTJOB","SBMDKTJOB"},
        		   {"SBMNETJOB","SBMNETJOB"},
        		   {"SELECT","SELECT"},
        		   {"SNDF","SNDF"},
        		   {"SNDJRNE","SNDJRNE"},
        		   {"SNDNETF","SNDNETF"},
        		   {"SNDNETSPLF","SNDNETSPLF"},
        		   {"SNDPGMMSG","SNDPGMMSG"},
        		   {"SNDRCVF","SNDRCVF"},
        		   {"SNDTCPSPLF","SNDTCPSPLF"},
        		   {"STRCMTCTL","STRCMTCTL"},
        		   {"STRCPYSCN","STRCPYSCN"},
        		   {"STRDBMON","STRDBMON"},
        		   {"STRDBRDR","STRDBRDR"},
        		   {"STRDIGQRY","STRDIGQRY"},
        		   {"STRDKTRDR","STRDKTRDR"},
        		   {"STRDKTWTR","STRDKTWTR"},
        		   {"STRJRNAP","STRJRNAP"},
        		   {"STRJRNPF","STRJRNPF"},
        		   {"STRPGMMNU","STRPGMMNU"},
        		   {"STRPJ","STRPJ"},
        		   {"STRPRTEML","STRPRTEML"},
        		   {"STRPRTWTR","STRPRTWTR"},
        		   {"TFRBCHJOB","TFRBCHJOB"},
        		   {"TFRJOB","TFRJOB"},
        		   {"TRNCKMKSF","TRNCKMKSF"},
        		   {"UPDPGM","UPDPGM"},
        		   {"UPDSRVPGM","UPDSRVPGM"},
        		   {"VFYSRVCFG","VFYSRVCFG"},
        		   {"VFYTCPCNN","VFYTCPCNN"},
        		   {"WAIT","WAIT"},
        		   {"WHEN","WHEN"},
        		   {"WRKCMTDFN","WRKCMTDFN"},
        		   {"WRKFTRSLTE","WRKFTRSLTE"},
        		   {"WRKJOB","WRKJOB"},
        		   {"WRKJOBQ","WRKJOBQ"},
        		   {"WRKJOBQD","WRKJOBQD"},
        		   {"WRKJVMJOB","WRKJVMJOB"},
        		   {"WRKMSG","WRKMSG"},
        		   {"WRKOBJLCK","WRKOBJLCK"},
        		   {"WRKOPTF","WRKOPTF"},
        		   {"WRKOUTQ","WRKOUTQ"},
        		   {"WRKOUTQD","WRKOUTQD"},
        		   {"WRKPRTSTS","WRKPRTSTS"},
        		   {"WRKRDR","WRKRDR"},
        		   {"WRKSPLFA","WRKSPLFA"},
        		   {"WRKSYSSTS","WRKSYSSTS"},
        		   {"WRKTCPPTP","WRKTCPPTP"},
        		   {"WRKWTR","WRKWTR"},
*/
           } ;

           boolean passed = true;
           
           // create a CommandHelpRetriever
           for (int commandIndex = 0; commandIndex < commandsAndExpectedStrings.length; commandIndex++) {
               String[] commandAndExpected = commandsAndExpectedStrings[commandIndex]; 

               CommandHelpRetriever commandHelp = new CommandHelpRetriever();
               CommandList cmdList = new CommandList(systemObject_, "QSYS", commandAndExpected[0]);
               Command[] cmds = cmdList.generateList();
               System.out.println("-->Command="+commandAndExpected[0]); 
               sb.append("\n-->Command="+commandAndExpected[0]+"\n");
               try {
                   if (cmds.length == 0) {
                       System.out.println("Warning:  Command "+commandAndExpected[0]+" did not generate list");
                       sb.append(          "Warning:  Command "+commandAndExpected[0]+" did not generate list\n");
                   } else { 
                       String help = commandHelp.generateHTML(cmds[0]);

                       if (help == null) {
                           sb.append("FAILED:  Command help is empty\n");
                           passed = false; 
                       } else {
                           for (int i = 1; i < commandAndExpected.length; i++) {
                               if (help.indexOf(commandAndExpected[i]) < 0) {
                                   sb.append("FAILED: Did not find expected string "+commandAndExpected[i]+"\n");
                                   sb.append("Returned help was : "+help+"\n"); 
                                   passed = false; 
                               } 
                           }
                       }
                   }
               } catch (Exception e) {
                   // Ignore any not authorized or not available 
                   String eMessage = e.toString();
                   if (eMessage.indexOf("CPF9802") >= 0 || eMessage.indexOf("CPF6E3B") >= 0  ) {
                       System.out.println("Warning:  Ignoring exception: "+eMessage);
                       sb.append("Warning: On "+commandAndExpected[0]+" Ignoring exception: "+eMessage+"\n");
                   } else { 
                       passed = false;
                       sb.append("FAILED: On "+commandAndExpected[0]+" Exception taken "+e.toString()+"\n");
                       printStackTraceToStringBuffer(e, sb);
                      
                   }
               } 
           }
           assertCondition(passed, sb.toString());

       }
       catch(Exception e)
       {
           failed(e, "Unexpected exception."+sb.toString());

           System.out.flush(); 
           System.err.flush();
           System.out.println("===================================="); 
           System.out.flush(); 
           System.err.flush();
           Throwable cause = e.getCause();
           while (cause != null) {
               System.out.flush(); 
               System.err.flush();
               System.out.println("Caused by ");
               System.out.flush();
               System.err.flush(); 
               cause.printStackTrace();
               cause = cause.getCause();
           } 

       }


   }






}


